#!/usr/bin/env sh
set -eu

ROOT=${NEMACS_NEXT_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")/../../.." && pwd -P)}
EMACS=${EMACS:-emacs}

"$EMACS" -Q --batch \
  -L "$ROOT/src" \
  -L "$ROOT/apps/nemacs-next/lisp" \
  --eval "(require 'nemacs-next-protocol)" \
  --eval "(let ((missing (nemacs-next-missing-required-packages))) (when missing (error \"missing required packages: %S\" missing)))" \
  --eval "(let ((hello (nemacs-next-session-handle-message '(:type hello)))) (unless (and (eq (plist-get hello :type) 'hello) (= (plist-get hello :protocol-version) nemacs-next-protocol-version)) (error \"bad hello: %S\" hello)))" \
  --eval "(let* ((created (nemacs-next-session-handle-message '(:type command :name create-buffer :buffer-name \"nemacs-next-smoke\"))) (inserted (nemacs-next-session-handle-message '(:type command :name insert-text :text \"abc\"))) (line (nemacs-next-protocol-encode-line inserted))) (unless (and (equal (plist-get created :buffer-name) \"nemacs-next-smoke\") (eq (plist-get inserted :type) 'snapshot) (equal (plist-get inserted :buffer-name) \"nemacs-next-smoke\") (equal (plist-get inserted :text) \"abc\") (string-match-p \"\\\"type\\\":\\\"snapshot\\\"\" line) (string-match-p \"\\\"text\\\":\\\"abc\\\"\" line)) (error \"bad dispatcher snapshot/line: %S %S %S\" created inserted line)))" \
  --eval "(let* ((moved (nemacs-next-session-handle-message '(:type command :name goto-char :position 1))) (fwd (nemacs-next-session-handle-message '(:type command :name forward-char :count 2))) (back (nemacs-next-session-handle-message '(:type command :name backward-char :count 1))) (deleted (nemacs-next-session-handle-message '(:type command :name delete-char :count 1)))) (unless (and (= (plist-get moved :point) 1) (= (plist-get fwd :point) 3) (= (plist-get back :point) 2) (equal (plist-get deleted :text) \"ac\") (= (plist-get deleted :point) 2)) (error \"bad movement/delete sequence: %S %S %S %S\" moved fwd back deleted)))" \
  --eval "(let ((oor-goto (nemacs-next-session-handle-message '(:type command :name goto-char :position 999))) (oor-fwd (nemacs-next-session-handle-message '(:type command :name forward-char :count 999)))) (unless (and (eq (plist-get oor-goto :type) 'error) (eq (plist-get oor-goto :code) 'out-of-range) (eq (plist-get oor-fwd :type) 'error) (eq (plist-get oor-fwd :code) 'out-of-range)) (error \"bad out-of-range handling: %S %S\" oor-goto oor-fwd)))" \
  --eval "(let ((yank-empty (nemacs-next-session-handle-message '(:type command :name yank)))) (unless (and (eq (plist-get yank-empty :type) 'error) (eq (plist-get yank-empty :code) 'empty-kill-ring)) (error \"bad empty-kill-ring yank: %S\" yank-empty)))" \
  --eval "(let* ((nl (nemacs-next-session-handle-message '(:type command :name newline))) (un (nemacs-next-session-handle-message '(:type command :name undo)))) (unless (and (equal (plist-get nl :text) \"a\\nc\") (= (plist-get nl :point) 3) (equal (plist-get un :text) \"ac\") (= (plist-get un :point) 2)) (error \"bad newline/undo sequence: %S %S\" nl un)))" \
  --eval "(let* ((killed (nemacs-next-session-handle-message '(:type command :name kill-region :start 1 :end 2))) (yanked (nemacs-next-session-handle-message '(:type command :name yank)))) (unless (and (equal (plist-get killed :text) \"c\") (= (plist-get killed :point) 1) (equal (plist-get yanked :text) \"ac\") (= (plist-get yanked :point) 2)) (error \"bad kill-region/yank sequence: %S %S\" killed yanked)))" \
  --eval "(let* ((killed-line (nemacs-next-session-handle-message '(:type command :name kill-line))) (yanked-line (nemacs-next-session-handle-message '(:type command :name yank)))) (unless (and (equal (plist-get killed-line :text) \"a\") (= (plist-get killed-line :point) 2) (equal (plist-get yanked-line :text) \"ac\") (= (plist-get yanked-line :point) 3)) (error \"bad kill-line/yank sequence: %S %S\" killed-line yanked-line)))" \
  --eval "(let ((bad-kill (nemacs-next-session-handle-message '(:type command :name kill-region)))) (unless (and (eq (plist-get bad-kill :type) 'error) (eq (plist-get bad-kill :code) 'bad-command)) (error \"bad kill-region missing-args handling: %S\" bad-kill)))" \
  --eval "(let* ((_fresh (nemacs-next-session-handle-message '(:type command :name create-buffer :buffer-name \"nemacs-next-smoke-undo-empty\"))) (undo-empty (nemacs-next-session-handle-message '(:type command :name undo))) (alive (nemacs-next-session-handle-message '(:type command :name snapshot)))) (unless (and (eq (plist-get undo-empty :type) 'error) (eq (plist-get undo-empty :code) 'no-further-undo-information) (eq (plist-get alive :type) 'snapshot)) (error \"bad undo-empty-history / liveness handling: %S %S\" undo-empty alive)))" \
  --eval "(let* ((path (make-temp-file \"nemacs-next-m3-\" nil \".txt\" \"seed\")) (opened (nemacs-next-session-handle-message (list :type 'command :name 'find-file :path path))) (appended (nemacs-next-session-handle-message '(:type command :name insert-text :text \"!\"))) (saved (nemacs-next-session-handle-message '(:type command :name save-buffer))) (buffer-complete (nemacs-next-session-handle-message '(:type command :name complete :purpose buffer :input \"nemacs-next-m3\"))) (generic-complete (nemacs-next-session-handle-message '(:type command :name complete :input \"fi\" :collection (\"find-file\" \"save-buffer\" \"switch-to-buffer\")))) (switched (nemacs-next-session-handle-message '(:type command :name switch-to-buffer :buffer-name \"nemacs-next-smoke\"))) (killed (nemacs-next-session-handle-message (list :type 'command :name 'kill-buffer :buffer-name (plist-get opened :buffer-name)))) (missing-kill (nemacs-next-session-handle-message '(:type command :name kill-buffer :buffer-name \"missing-buffer\")))) (unless (and (eq (plist-get opened :type) 'snapshot) (equal (plist-get opened :file-name) path) (equal (plist-get opened :text) \"seed\") (equal (plist-get appended :text) \"seed!\") (equal (plist-get saved :saved-file) path) (equal (with-temp-buffer (insert-file-contents path) (buffer-string)) \"seed!\") (eq (plist-get buffer-complete :type) 'minibuffer) (member (plist-get opened :buffer-name) (plist-get buffer-complete :candidates)) (equal (plist-get generic-complete :candidates) '(\"find-file\")) (equal (plist-get switched :buffer-name) \"nemacs-next-smoke\") (eq (plist-get killed :type) 'snapshot) (eq (plist-get missing-kill :type) 'error) (eq (plist-get missing-kill :code) 'no-such-buffer)) (error \"bad M3 file/buffer/completion sequence: %S %S %S %S %S %S %S %S %S\" opened appended saved buffer-complete generic-complete switched killed missing-kill path)) (delete-file path))" \
  --eval "(let* ((frame (nemacs-next-session-handle-message '(:type command :name frame-snapshot :width 80 :height 4))) (rendered (nemacs-next-session-render-frame-text frame)) (menu (nemacs-next-session-handle-message '(:type command :name menu))) (toolbar (plist-get menu :default-toolbar)) (toolbar-commands (delq nil (mapcar (lambda (item) (and (not (plist-get item :separator)) (plist-get item :command))) toolbar))) (open-prompt (nemacs-next-session-handle-message '(:type command :name toolbar-invoke :id \"toolbar.open-file\"))) (search-prompt (nemacs-next-session-handle-message '(:type command :name toolbar-invoke :id \"toolbar.search\"))) (resize (nemacs-next-session-handle-message '(:type resize :width 22 :height 3))) (input (nemacs-next-session-handle-message '(:type input :event (:text \"x\")))) (ime (nemacs-next-session-handle-message '(:type input :event (:commit \"y\")))) (clip (nemacs-next-session-handle-message '(:type command :name clipboard-read)))) (unless (and (eq (plist-get frame :type) 'snapshot) (plist-get frame :frame) (= (length toolbar) 13) (equal toolbar-commands '(\"find-file\" \"find-file\" \"dired\" \"kill-buffer\" \"save-buffer\" \"undo\" \"kill-region\" \"copy-region-as-kill\" \"yank\" \"isearch-forward\")) (string-match-p \"nemacs-next-smoke\" rendered) (eq (plist-get menu :type) 'menu) (equal (plist-get (car (plist-get menu :items)) :command) \"find-file\") (eq (plist-get open-prompt :type) 'minibuffer) (eq (plist-get open-prompt :purpose) 'file) (eq (plist-get search-prompt :purpose) 'search) (eq (plist-get resize :type) 'delta) (eq (plist-get input :type) 'delta) (eq (plist-get ime :type) 'delta) (eq (plist-get clip :type) 'request)) (error \"bad M4 frame/menu/toolbar/input/clipboard sequence: %S %S %S %S %S %S %S %S %S\" frame rendered menu open-prompt search-prompt resize input ime clip)))" \
  --eval "(dolist (feature '(emacs-init nemacs-main nemacs-gtk-frontend nemacs-gui-file-bridge-runtime)) (when (featurep feature) (error \"loaded forbidden app/frontend feature: %S\" feature)))" \
  --eval "(princ (format \"nemacs-next-smoke: protocol=%s packages=%S ok\\n\" nemacs-next-protocol-version nemacs-next-required-library-packages))"
