;;; nelisp-emacs-editing-pkg.el --- package metadata -*- lexical-binding: t; no-byte-compile: t; -*-

;; Generated by scripts/nemacs-library-package-metadata.el.
;; Source of truth remains src/ and the package descriptor tooling.

(define-package
  "nelisp-emacs-editing"
  "0.1.0"
  "Reusable nelisp-emacs editing and undo helpers."
  '((nelisp-emacs-buffer-core "0.1.0") (nelisp-emacs-foundation "0.1.0"))
  :keywords '("emacs" "lisp" "nelisp" "compatibility" "buf")
  :url "https://github.com/zawatton/nelisp-emacs"
  :maintainer "zawatton"
  :authors '("zawatton")
  :license "GPL-3.0-or-later")

;;; nelisp-emacs-editing-pkg.el ends here
