;;; build-nelisp-bootstrap.el --- generate standalone bootstrap bundle  -*- lexical-binding: t; -*-

;;; Commentary:

;; Build helper for the NeLisp driver cold-start path.
;;
;; NeLisp v2 can run the runtime mostly as Elisp, but cold boot still
;; pays for many small source loads.  This script asks host Emacs to
;; load `nemacs-main', reads the resulting local `load-history', and
;; concatenates the participating src/*.el files in dependency order.
;; The generated file is still plain Elisp; it is a preload bundle, not
;; a bytecode/pdump replacement.

;;; Code:

(require 'cl-lib)

(defvar nelisp-bootstrap-output-file
  (expand-file-name "build/nemacs-bootstrap.el"
                    (expand-file-name ".." (file-name-directory
                                            (or load-file-name
                                                buffer-file-name))))
  "Output path for the generated NeLisp bootstrap bundle.")

(defvar nelisp-bootstrap-repl-output-file nil
  "Output path for the generated NeLisp REPL bootstrap input.
When nil, derive it from `nelisp-bootstrap-output-file' by replacing the
final `.el' suffix with `.repl'.")

(defvar nelisp-bootstrap-repo-root
  (expand-file-name ".." (file-name-directory
                          (or load-file-name buffer-file-name)))
  "Repository root used by the bundle generator.")

(defvar nelisp-bootstrap-extra-files
  '("cl-lib.el")
  "Local src files that host Emacs may not load but standalone NeLisp needs.")

(defun nelisp-bootstrap--src-dir ()
  "Return the absolute src directory."
  (file-name-as-directory
   (expand-file-name "src" nelisp-bootstrap-repo-root)))

(defun nelisp-bootstrap--vendor-dir ()
  "Return the absolute vendor directory."
  (file-name-as-directory
   (expand-file-name "vendor" nelisp-bootstrap-repo-root)))

(defun nelisp-bootstrap--src-file-p (file)
  "Return non-nil when FILE is a local src/*.el file."
  (let ((src (nelisp-bootstrap--src-dir))
        (abs (and (stringp file) (expand-file-name file))))
    (and abs
         (string-prefix-p src abs)
         (string-suffix-p ".el" abs)
         (file-readable-p abs))))

(defun nelisp-bootstrap--collect-loaded-src-files ()
  "Return loaded local src files in dependency-first order."
  (let (files)
    (dolist (entry load-history)
      (let ((file (car-safe entry)))
        (when (nelisp-bootstrap--src-file-p file)
          (push (expand-file-name file) files))))
    (delete-dups files)))

(defun nelisp-bootstrap--insert-after (file anchor files)
  "Insert FILE after ANCHOR in FILES, unless FILE is already present."
  (let ((file (expand-file-name file))
        (anchor (expand-file-name anchor)))
    (cond
     ((member file files) files)
     ((not (member anchor files)) (cons file files))
     (t
      (let (out rest done)
        (setq rest files)
        (while rest
          (push (car rest) out)
          (when (equal (car rest) anchor)
            (push file out)
            (setq done t))
          (setq rest (cdr rest)))
        (unless done
          (push file out))
        (nreverse out))))))

(defun nelisp-bootstrap--complete-file-list (files)
  "Add standalone-only source files to FILES in a dependency-safe spot."
  (let ((src (nelisp-bootstrap--src-dir))
        (out files))
    (dolist (name nelisp-bootstrap-extra-files)
      (let ((file (expand-file-name name src))
            (anchor (expand-file-name "emacs-cl-macros.el" src)))
        (when (file-readable-p file)
          (setq out (nelisp-bootstrap--insert-after file anchor out)))))
    out))

(defun nelisp-bootstrap--write-bundle (files output)
  "Write FILES into OUTPUT as one lexical-binding Elisp bundle."
  (make-directory (file-name-directory output) t)
  ;; NeLisp's current `load' prefers OUTPUT.elc even when OUTPUT ends in
  ;; ".el".  Remove stale byte-compiled companions so the bootstrap
  ;; bundle stays a plain-Elisp preload file.
  (let ((compiled (concat output "c")))
    (when (file-exists-p compiled)
      (delete-file compiled)))
  (with-temp-buffer
    (insert ";;; nemacs-bootstrap.el --- generated NeLisp bootstrap bundle  -*- lexical-binding: t; -*-\n")
    (insert ";;; Generated by scripts/build-nelisp-bootstrap.el; do not edit.\n\n")
    (dolist (file files)
      (let ((rel (file-relative-name file nelisp-bootstrap-repo-root)))
        (insert "\n;;; >>> " rel "\n")
        (insert-file-contents file)
        (goto-char (point-max))
        (insert "\n;;; <<< " rel "\n")))
    (let ((coding-system-for-write 'utf-8-emacs-unix))
      (write-region (point-min) (point-max) output nil 'silent))))

(defun nelisp-bootstrap--read-forms-from-file (file)
  "Return top-level forms read from FILE."
  (with-temp-buffer
    (insert-file-contents file)
    (let ((forms nil))
      (goto-char (point-min))
      (condition-case err
          (while t
            (push (read (current-buffer)) forms))
        (end-of-file nil)
        (error
         (error "cannot read %s: %S" file err)))
      (nreverse forms))))

(defun nelisp-bootstrap--one-line-string-literal (string)
  "Return STRING as an Elisp string literal that fits on one line."
  (let ((literal (prin1-to-string string)))
    (setq literal (replace-regexp-in-string "\n" "\\\\n" literal t t))
    (setq literal (replace-regexp-in-string "\r" "\\\\r" literal t t))
    literal))

(defun nelisp-bootstrap--write-repl-bundle (files output)
  "Write FILES into OUTPUT as standalone-reader REPL input.

The standalone reader's persistent development surface is the REPL.
Most forms go through `nelisp--eval-source-string', matching the source
loader path.  Buffer substrate files are emitted as direct REPL forms
because their `cl-defstruct' accessors and setters must be installed in
the live REPL context for immediate redefinition."
  (make-directory (file-name-directory output) t)
  (with-temp-buffer
    (insert ";;; nemacs-bootstrap.repl --- generated NeLisp bootstrap REPL input\n")
    (insert ";;; Generated by scripts/build-nelisp-bootstrap.el; do not edit.\n")
    (dolist (file files)
      (let ((rel (file-relative-name file nelisp-bootstrap-repo-root)))
        (insert "\n;;; >>> " rel "\n")
        (dolist (form (nelisp-bootstrap--read-forms-from-file file))
          (if (member rel '("src/nelisp-text-buffer.el"
                            "src/nelisp-emacs-compat.el"))
              (progn
                (insert "(progn ")
                (insert (let ((print-escape-newlines t))
                          (prin1-to-string form)))
                (insert " nil)\n"))
            (insert "(progn (nelisp--eval-source-string ")
            (insert (nelisp-bootstrap--one-line-string-literal
                     (let ((print-escape-newlines t))
                       (prin1-to-string form))))
            (insert ") nil)\n")))
        (insert ";;; <<< " rel "\n")))
    (let ((coding-system-for-write 'utf-8-emacs-unix))
      (write-region (point-min) (point-max) output nil 'silent))))

(defun nelisp-bootstrap-build-batch ()
  "Generate `nelisp-bootstrap-output-file' and print a short summary."
  (let* ((src (nelisp-bootstrap--src-dir))
         (vendor (nelisp-bootstrap--vendor-dir))
         (nelisp-emacs-vendor-root (directory-file-name vendor)))
    (add-to-list 'load-path src)
    (add-to-list 'load-path (expand-file-name "emacs-lisp" vendor) t)
    (add-to-list 'load-path (expand-file-name "emacs-lisp/emacs-lisp" vendor) t)
    (require 'nemacs-main)
    (let* ((files (nelisp-bootstrap--complete-file-list
                   (nelisp-bootstrap--collect-loaded-src-files)))
           (output (expand-file-name nelisp-bootstrap-output-file))
           (repl-output
            (expand-file-name
             (or nelisp-bootstrap-repl-output-file
                 (concat (file-name-sans-extension output) ".repl")))))
      (nelisp-bootstrap--write-bundle files output)
      (nelisp-bootstrap--write-repl-bundle files repl-output)
      (princ (format "nelisp-bootstrap bundle=%s repl=%s files=%d\n"
                     output repl-output (length files))))))

(provide 'build-nelisp-bootstrap)

;;; build-nelisp-bootstrap.el ends here
