;;; char-table-standalone-probe.el --- standalone aref/aset checks  -*- lexical-binding: t; -*-

(let ((checks 0)
      (parent (make-char-table 'probe 'parent-default))
      (child (make-char-table 'probe)))
  (dolist (entry '((0 . zero) (1 . one) (6 . six)
                   (97 . ascii) (#x3042 . unicode)))
    (aset child (car entry) (cdr entry))
    (unless (eq (aref child (car entry)) (cdr entry))
      (error "char-table roundtrip failed: %S" entry))
    (setq checks (1+ checks)))
  (aset parent ?z 'parent-ascii)
  (set-char-table-parent child parent)
  (unless (eq (aref child ?z) 'parent-ascii)
    (error "char-table parent fallback failed"))
  (setq checks (1+ checks))
  (unless (eq (aref child #x4000) 'parent-default)
    (error "char-table parent default failed"))
  (setq checks (1+ checks))
  (unless (aref (standard-syntax-table) ?a)
    (error "standard syntax table aref failed"))
  (setq checks (1+ checks))
  (let ((ordinary [a b c]))
    (unless (eq (aset ordinary 1 'changed) 'changed)
      (error "ordinary vector aset return failed"))
    (unless (eq (aref ordinary 1) 'changed)
      (error "ordinary vector delegation failed")))
  (setq checks (1+ checks))
  (let ((ordinary "abc"))
    (unless (= (aset ordinary 1 ?z) ?z)
      (error "ordinary string aset return failed"))
    (unless (= (aref ordinary 1) ?z)
      (error "ordinary string delegation failed")))
  (setq checks (1+ checks))
  (let ((caught nil))
    (condition-case _err
        (aref child -1)
      (wrong-type-argument (setq caught t)))
    (unless caught
      (error "char-table bounds validation failed")))
  (setq checks (1+ checks))
  (let ((default-parent (make-char-table 'probe 'parent-default))
        (default-child (make-char-table 'probe 'child-default)))
    (set-char-table-parent default-child default-parent)
    (dolist (index (list ?a #x3042 (max-char)))
      (unless (eq (aref default-child index) 'child-default)
        (error "own default did not precede parent: %d" index))
      (setq checks (1+ checks))
      (aset default-child index nil)
      (unless (eq (aref default-child index) 'child-default)
        (error "explicit nil did not use own default: %d" index))
      (setq checks (1+ checks)))
    (set-char-table-range default-child nil 'changed)
    (dolist (index (list ?a #x3042 (max-char)))
      (unless (eq (aref default-child index) 'changed)
        (error "changed default was not visible: %d" index))
      (setq checks (1+ checks))))
  (load (expand-file-name "../src/emacs-char-table.el"
                          (file-name-directory
                           (or load-file-name buffer-file-name))))
  (unless (eq (aref child ?a) 'ascii)
    (error "reload changed char-table bridge"))
  (setq checks (1+ checks))
  (unless (= checks 21)
    (error "char-table probe incomplete: count=%d" checks))
  (princ (format "CHAR-TABLE-BRIDGE=ok count=%d\n" checks)))

;;; char-table-standalone-probe.el ends here
