;;; extract-elprop-forms.el --- extract pure should-forms from host ERT (Doc 03 §6.3) -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:
;; Parse host ERT `*-tests.el' files, extract the payload of `should' /
;; `should-not' / `should-error' calls, keep only PURE forms (no buffer / IO
;; / state side-effects), and emit a corpus consumable by `bin/elprop-run'.
;;
;; Batch: ELPROP_SRC = space/colon-separated test files; ELPROP_OUT = output
;; corpus path (writing is opt-in so the curated seed is never clobbered).

;;; Code:

(require 'cl-lib)

(defconst elprop-extract--impure-symbols
  '(setq setq-default setf cl-incf cl-decf push pop
    with-temp-buffer with-temp-file with-current-buffer save-excursion
    save-restriction save-current-buffer set-buffer get-buffer-create
    generate-new-buffer kill-buffer insert insert-char delete-region
    delete-char erase-buffer goto-char forward-char backward-char
    point point-min point-max buffer-string buffer-substring
    current-buffer set-mark region-beginning region-end narrow-to-region
    message princ print prin1 terpri read read-from-minibuffer
    find-file write-region make-temp-file delete-file copy-file
    rename-file make-directory call-process shell-command
    random current-time float-time current-time-string format-time-string
    sleep-for sit-for run-at-time make-network-process
    set-buffer-modified-p switch-to-buffer pop-to-buffer
    define-key global-set-key add-hook remove-hook run-hooks
    provide require load expand-file-name getenv)
  "Symbols whose presence marks a form as impure (state/IO-dependent).")

(defun elprop-extract--pure-p (form)
  "Return non-nil when FORM contains no impure symbol anywhere in its tree."
  (catch 'impure
    (cl-labels ((walk (x)
                  (cond
                   ((and (symbolp x) (memq x elprop-extract--impure-symbols))
                    (throw 'impure nil))
                   ((consp x) (walk (car x)) (walk (cdr x))))))
      (walk form))
    t))

(defun elprop-extract--should-forms (sexp)
  "Return a list of (TYPE . PAYLOAD-FORM) from SEXP's should-calls."
  (let (acc)
    (cl-labels ((walk (x)
                  (when (consp x)
                    (pcase (car x)
                      ('should
                       (when (cadr x) (push (cons 'value (cadr x)) acc)))
                      ('should-not
                       (when (cadr x) (push (cons 'value (list 'not (cadr x))) acc)))
                      ('should-error
                       (when (cadr x) (push (cons 'error (cadr x)) acc))))
                    (dolist (e (cdr x)) (walk e)))))
      (walk sexp))
    (nreverse acc)))

(defun elprop-extract-file (file)
  "Extract pure should-payload entries from ERT FILE.
Return a list of (:id ID :type TYPE :form FORM) plists."
  (let ((base (file-name-base file))
        (tops (with-temp-buffer
                (insert-file-contents file)
                (goto-char (point-min))
                (let (acc form)
                  (condition-case nil
                      (while t (setq form (read (current-buffer))) (push form acc))
                    (end-of-file nil))
                  (nreverse acc))))
        (n 0) out)
    (dolist (top tops)
      (dolist (pair (elprop-extract--should-forms top))
        (when (elprop-extract--pure-p (cdr pair))
          (setq n (1+ n))
          (push (list :id (format "%s-%03d" base n)
                      :type (car pair)
                      :form (cdr pair))
                out))))
    (nreverse out)))

(defun elprop-extract-batch ()
  "Batch entry: extract from ELPROP_SRC files, optionally write ELPROP_OUT."
  (let* ((src (or (getenv "ELPROP_SRC") ""))
         (files (split-string src "[ :\n]+" t))
         (out (getenv "ELPROP_OUT"))
         (all '()))
    (dolist (f files)
      (if (file-readable-p f)
          (setq all (append all (elprop-extract-file f)))
        (princ (format "elprop-extract: skip unreadable %s\n" f))))
    (princ (format "elprop-extract: %d file(s), %d pure forms\n"
                   (length files) (length all)))
    (when (and out all)
      (let ((base (file-name-nondirectory out)))
        (with-temp-file out
          (insert ";;; " base " --- extracted property-comparison forms -*- lexical-binding: t; -*-\n")
          (insert ";; Generated by scripts/extract-elprop-forms.el -- do not edit by hand.\n")
          (insert ";;; Code:\n\n(defvar elprop-forms\n  '(")
          (let ((first t))
            (dolist (e all)
              (insert (if first "" "\n    "))
              (setq first nil)
              (insert (format "(:id %S :type %s :form %S)"
                              (plist-get e :id)
                              (plist-get e :type)
                              (plist-get e :form)))))
          (insert "))\n\n(provide 'elprop-forms-auto)\n")
          (insert ";;; " base " ends here\n")))
      (princ (format "elprop-extract: wrote %s\n" out)))))

(provide 'extract-elprop-forms)
;;; extract-elprop-forms.el ends here
