;;; nemacs-library-package-guide.el --- consumer package guide -*- lexical-binding: t; -*-

;;; Commentary:

;; Generate consumer-facing package guide artifacts from the draft package
;; descriptors.  The guide is intentionally derived from the facade
;; manifest/dependency tooling instead of being hand-maintained.

;;; Code:

(require 'cl-lib)
(require 'subr-x)
(require 'nemacs-library-package-descriptors)

(defvar nemacs-library-package-guide-repo-root
  (expand-file-name ".." (file-name-directory
                          (or load-file-name buffer-file-name)))
  "Repository root.")

(defvar nemacs-library-package-guide-output
  (expand-file-name "build/nemacs-library-package-guide.tsv"
                    nemacs-library-package-guide-repo-root)
  "TSV output path.")

(defvar nemacs-library-package-guide-summary-output
  (expand-file-name "build/nemacs-library-package-guide.org"
                    nemacs-library-package-guide-repo-root)
  "Org guide output path.")

(defun nemacs-library-package-guide--symbol-name (value)
  "Return VALUE as a stable string."
  (if (symbolp value) (symbol-name value) (format "%s" value)))

(defun nemacs-library-package-guide--join (values)
  "Return VALUES as a comma-separated stable string."
  (mapconcat #'identity
             (sort (delete-dups
                    (mapcar #'nemacs-library-package-guide--symbol-name
                            (copy-sequence values)))
                   #'string<)
             ","))

(defun nemacs-library-package-guide--tsv-cell (value)
  "Return VALUE formatted as one TSV cell."
  (replace-regexp-in-string "[\t\n\r]+" " " (format "%s" (or value ""))))

(defun nemacs-library-package-guide--row (&rest cells)
  "Return CELLS as a TSV line."
  (mapconcat #'nemacs-library-package-guide--tsv-cell cells "\t"))

(defun nemacs-library-package-guide--descriptor-rows ()
  "Return descriptor rows as generated by descriptor tooling."
  (nemacs-library-package-descriptors--descriptor-rows))

(defun nemacs-library-package-guide--dependency-package-ids (descriptor)
  "Return package ids required by DESCRIPTOR."
  (mapcar #'nemacs-library-package-descriptors--package-id
          (nth 6 descriptor)))

(defun nemacs-library-package-guide--consumer-row (descriptor)
  "Return consumer guide row for DESCRIPTOR."
  (let ((requires
         (nemacs-library-package-guide--dependency-package-ids descriptor)))
    (list (nth 1 descriptor)
          (nth 0 descriptor)
          (nth 2 descriptor)
          (nth 3 descriptor)
          requires
          (nth 4 descriptor)
          (nth 7 descriptor)
          (nth 9 descriptor)
          (nth 10 descriptor)
          (length (nth 5 descriptor))
          (length (nth 8 descriptor)))))

(defun nemacs-library-package-guide--rows ()
  "Return consumer package guide rows."
  (mapcar #'nemacs-library-package-guide--consumer-row
          (nemacs-library-package-guide--descriptor-rows)))

(defun nemacs-library-package-guide--write-tsv (rows output)
  "Write consumer guide ROWS to TSV OUTPUT."
  (make-directory (file-name-directory output) t)
  (with-temp-file output
    (insert
     (nemacs-library-package-guide--row
      "package_id" "facade_name" "owner" "loader_feature"
      "package_requires" "member_features" "lazy_features"
      "host_features" "vendor_package_features" "eager_source_count"
      "lazy_source_count")
     "\n")
    (dolist (row rows)
      (insert
       (nemacs-library-package-guide--row
        (nth 0 row)
        (nth 1 row)
        (nth 2 row)
        (nth 3 row)
        (nemacs-library-package-guide--join (nth 4 row))
        (nemacs-library-package-guide--join (nth 5 row))
        (nemacs-library-package-guide--join (nth 6 row))
        (nemacs-library-package-guide--join (nth 7 row))
        (nemacs-library-package-guide--join (nth 8 row))
        (nth 9 row)
        (nth 10 row))
       "\n"))))

(defun nemacs-library-package-guide--write-summary (rows output)
  "Write consumer package guide ROWS to Org OUTPUT."
  (make-directory (file-name-directory output) t)
  (with-temp-file output
    (insert "#+TITLE: nemacs library package consumer guide\n\n")
    (insert (format "* Summary\n\n- packages: %d\n\n" (length rows)))
    (insert "* Entry points\n\n")
    (insert "External consumers should prefer the top-level facade:\n\n")
    (insert "#+begin_src emacs-lisp\n")
    (insert "(add-to-list 'load-path \"/path/to/nelisp-emacs/src\")\n")
    (insert "(require 'nelisp-emacs)\n")
    (insert "#+end_src\n\n")
    (insert "A future package extraction may also expose the package loader features below directly.\n")
    (insert "These loader features are already required independently by the package smoke gate.\n\n")
    (insert "* Packages\n\n")
    (dolist (row rows)
      (insert (format "** %s\n\n" (nth 0 row)))
      (insert (format "- facade-name: =%s=\n" (nth 1 row)))
      (insert (format "- owner: =%s=\n" (nth 2 row)))
      (insert "- load:\n\n")
      (insert "#+begin_src emacs-lisp\n")
      (insert (format "(require '%s)\n" (nth 3 row)))
      (insert "#+end_src\n\n")
      (insert (format "- package-requires: =%s=\n"
                      (nemacs-library-package-guide--join (nth 4 row))))
      (insert (format "- member-features: =%s=\n"
                      (nemacs-library-package-guide--join (nth 5 row))))
      (insert (format "- lazy-features: =%s=\n"
                      (nemacs-library-package-guide--join (nth 6 row))))
      (insert (format "- host-features: =%s=\n"
                      (nemacs-library-package-guide--join (nth 7 row))))
      (insert (format "- vendor-package-features: =%s=\n"
                      (nemacs-library-package-guide--join (nth 8 row))))
      (insert (format "- source-counts: eager=%d lazy=%d\n\n"
                      (nth 9 row)
                      (nth 10 row))))
    (insert "* Notes\n\n")
    (insert "- This guide is generated from the descriptor drafts, not hand-maintained.\n")
    (insert "- =package-requires= names future package ids; current source-tree use should add =src/= to =load-path=.\n")
    (insert "- =lazy-features= are package-owned companions intentionally kept out of facade eager loads.\n")
    (insert "- Host and vendor features are not bundled by the current facade package descriptors.\n")))

;;;###autoload
(defun nemacs-library-package-guide-batch ()
  "Write library package consumer guide artifacts."
  (let ((rows (nemacs-library-package-guide--rows)))
    (unless rows
      (error "empty nelisp-emacs library package guide"))
    (nemacs-library-package-guide--write-tsv
     rows nemacs-library-package-guide-output)
    (nemacs-library-package-guide--write-summary
     rows nemacs-library-package-guide-summary-output)
    (princ
     (format
      "nemacs-library-package-guide: packages=%d output=%s summary=%s\n"
      (length rows)
      nemacs-library-package-guide-output
      nemacs-library-package-guide-summary-output))))

(provide 'nemacs-library-package-guide)

;;; nemacs-library-package-guide.el ends here
