;;; nemacs-library-package-layout.el --- draft packages/ layout plan -*- lexical-binding: t; -*-

;;; Commentary:

;; Generate a physical layout plan from the logical package descriptor
;; drafts.  This deliberately does not move files.  It gives humans and
;; future tooling a deterministic review artifact for the eventual
;; packages/ split.

;;; Code:

(require 'cl-lib)
(require 'subr-x)
(require 'nemacs-library-package-descriptors)

(defvar nemacs-library-package-layout-repo-root
  (expand-file-name ".." (file-name-directory
                          (or load-file-name buffer-file-name)))
  "Repository root.")

(defvar nemacs-library-package-layout-output
  (expand-file-name "build/nemacs-library-package-layout.tsv"
                    nemacs-library-package-layout-repo-root)
  "TSV output path.")

(defvar nemacs-library-package-layout-summary-output
  (expand-file-name "build/nemacs-library-package-layout.org"
                    nemacs-library-package-layout-repo-root)
  "Org summary output path.")

(defun nemacs-library-package-layout--tsv-cell (value)
  "Return VALUE formatted as one TSV cell."
  (replace-regexp-in-string "[\t\n\r]+" " " (format "%s" (or value ""))))

(defun nemacs-library-package-layout--row (&rest cells)
  "Return CELLS as a TSV line."
  (mapconcat #'nemacs-library-package-layout--tsv-cell cells "\t"))

(defun nemacs-library-package-layout--split (value)
  "Split comma-separated VALUE into strings."
  (if (or (null value) (equal value ""))
      nil
    (split-string value "," t)))

(defun nemacs-library-package-layout--target-path
    (package-id role source)
  "Return target path for PACKAGE-ID ROLE and SOURCE."
  (format "packages/%s/%s/%s"
          package-id
          (if (equal role "lazy") "lazy" "lisp")
          (file-name-nondirectory source)))

(defun nemacs-library-package-layout--descriptor-rows ()
  "Return descriptor rows as generated by descriptor tooling."
  (nemacs-library-package-descriptors--descriptor-rows))

(defun nemacs-library-package-layout--rows ()
  "Return physical package layout rows."
  (let (rows seen)
    (dolist (descriptor (nemacs-library-package-layout--descriptor-rows))
      (let* ((facade-name (nth 0 descriptor))
             (package-id (nth 1 descriptor))
             (owner (nth 2 descriptor))
             (loader (nth 3 descriptor))
             (eager-files (nth 5 descriptor))
             (lazy-features (nth 7 descriptor))
             (lazy-files (nth 8 descriptor))
             (requires
              (mapcar #'nemacs-library-package-descriptors--package-id
                      (nth 6 descriptor))))
        (dolist (source eager-files)
          (let ((key (list package-id "eager" source)))
            (unless (member key seen)
              (push key seen)
              (push (list package-id facade-name owner loader "eager"
                          source
                          (nemacs-library-package-layout--target-path
                           package-id "eager" source)
                          ""
                          (nemacs-library-package-descriptors--join requires))
                    rows))))
        (let ((sources lazy-files)
              (features lazy-features))
          (while sources
            (let* ((source (car sources))
                   (feature (car features))
                   (key (list package-id "lazy" source)))
              (unless (member key seen)
                (push key seen)
                (push (list package-id facade-name owner loader "lazy"
                            source
                            (nemacs-library-package-layout--target-path
                             package-id "lazy" source)
                            feature
                            (nemacs-library-package-descriptors--join requires))
                      rows)))
            (setq sources (cdr sources))
            (setq features (cdr features))))))
    (sort (nreverse rows)
          (lambda (a b)
            (string<
             (mapconcat (lambda (cell) (format "%s" cell)) a "\t")
             (mapconcat (lambda (cell) (format "%s" cell)) b "\t"))))))

(defun nemacs-library-package-layout--count-by-package (rows)
  "Return hash table of ROWS counts by package and role."
  (let ((table (make-hash-table :test 'equal)))
    (dolist (row rows)
      (let ((key (format "%s\t%s" (nth 0 row) (nth 4 row))))
        (puthash key (1+ (or (gethash key table) 0)) table)))
    table))

(defun nemacs-library-package-layout--sorted-counts (table)
  "Return TABLE counts sorted by key."
  (let (items)
    (maphash (lambda (key value) (push (cons key value) items)) table)
    (sort items (lambda (a b) (string< (car a) (car b))))))

(defun nemacs-library-package-layout--write-tsv (rows output)
  "Write ROWS to TSV OUTPUT."
  (make-directory (file-name-directory output) t)
  (with-temp-file output
    (insert
     (nemacs-library-package-layout--row
      "package_id" "facade_name" "owner" "loader_feature" "role"
      "source_file" "target_file" "lazy_feature" "package_requires")
     "\n")
    (dolist (row rows)
      (insert (apply #'nemacs-library-package-layout--row row) "\n"))))

(defun nemacs-library-package-layout--write-summary (rows output)
  "Write ROWS summary to Org OUTPUT."
  (let ((counts (nemacs-library-package-layout--count-by-package rows)))
    (make-directory (file-name-directory output) t)
    (with-temp-file output
      (insert "#+TITLE: nemacs library package layout plan\n\n")
      (insert (format "* Summary\n\n- file mappings: %d\n\n" (length rows)))
      (insert "** By package and role\n\n")
      (insert "| Package | Role | Files |\n|---------+------+-------|\n")
      (dolist (item (nemacs-library-package-layout--sorted-counts counts))
        (let* ((parts (split-string (car item) "\t"))
               (package (car parts))
               (role (cadr parts)))
          (insert (format "| %s | %s | %d |\n"
                          package role (cdr item)))))
      (insert "\n* Layout\n\n")
      (dolist (row rows)
        (insert (format "- =%s= -> =%s= (%s, %s)\n"
                        (nth 5 row)
                        (nth 6 row)
                        (nth 0 row)
                        (nth 4 row))))
      (insert "\n* Notes\n\n")
      (insert "- This is a move plan only; it does not move files.\n")
      (insert "- Eager files map to =packages/PACKAGE/lisp/=.\n")
      (insert "- Lazy files map to =packages/PACKAGE/lazy/= until their load-time policy is finalized.\n")
      (insert "- Keep facade/query APIs stable while experimenting with physical layout.\n"))))

;;;###autoload
(defun nemacs-library-package-layout-batch ()
  "Write library package layout artifacts."
  (let ((rows (nemacs-library-package-layout--rows)))
    (unless rows
      (error "empty nelisp-emacs library package layout"))
    (nemacs-library-package-layout--write-tsv
     rows nemacs-library-package-layout-output)
    (nemacs-library-package-layout--write-summary
     rows nemacs-library-package-layout-summary-output)
    (princ
     (format
      "nemacs-library-package-layout: mappings=%d output=%s summary=%s\n"
      (length rows)
      nemacs-library-package-layout-output
      nemacs-library-package-layout-summary-output))))

(provide 'nemacs-library-package-layout)

;;; nemacs-library-package-layout.el ends here
