;;; nemacs-wrap-init.el --- wrap user init forms for isolated loading -*- lexical-binding: t; -*-

;; Copyright (C) 2026 zawatton + Claude

;; This file is part of nelisp-emacs.

;;; Commentary:

;; M15 user-init lane — host-side generator.  Reads the user's
;; ~/.nemacs.d/early-init.el + init.el, splits them into top-level
;; forms, and emits a wrapped file where every form is bracketed by
;; `nemacs-init--begin' / `nemacs-init--ok' marker calls (defined by
;; the bridge runtime).  On the standalone reader a failing form
;; hard-aborts only itself under per-form loading, so the marker that
;; never fires identifies exactly which forms the substrate could not
;; apply — the bridge writes that as the nemacs-init-report transport
;; file instead of dying silently.
;;
;; Run under HOST Emacs (the splitter is just `read'):
;;   emacs -Q --batch -l scripts/nemacs-wrap-init.el \
;;     --eval '(nemacs-wrap-init "OUT" "early-init.el" "init.el")'

;;; Code:

(defun nemacs-wrap-init--forms (file)
  "Read all top-level forms of FILE; return a list of forms."
  (when (file-readable-p file)
    (with-temp-buffer
      (insert-file-contents file)
      (goto-char (point-min))
      (let ((forms nil))
        (condition-case nil
            (while t
              (push (read (current-buffer)) forms))
          (end-of-file nil)
          (invalid-read-syntax nil))
        (nreverse forms)))))

(defun nemacs-wrap-init--hint (form)
  "A short single-line description of FORM for the report."
  (let ((s (prin1-to-string form)))
    (setq s (replace-regexp-in-string "[\n\t]" " " s))
    (if (> (length s) 72)
        (concat (substring s 0 72) "...")
      s)))

(defun nemacs-wrap-init--lower (form)
  "Lower FORM to the runtime-image dialect the bridge executes.
The image replay evaluator does not wire `defun' / `defvar' /
`defconst' / `defcustom' (the substrate's own convention is
setq + fset), so the generator rewrites them; everything else
passes through verbatim and either applies or lands in the
report's failed list."
  (cond
   ((not (consp form)) form)
   ((and (eq (car form) 'defun) (>= (length form) 3))
    `(fset ',(nth 1 form) (lambda ,(nth 2 form) ,@(nthcdr 3 form))))
   ((and (memq (car form) '(defvar defcustom)) (>= (length form) 3))
    `(if (boundp ',(nth 1 form)) nil (setq ,(nth 1 form) ,(nth 2 form))))
   ((and (eq (car form) 'defconst) (>= (length form) 3))
    `(setq ,(nth 1 form) ,(nth 2 form)))
   (t form)))

(defun nemacs-wrap-init (out &rest files)
  "Write the wrapped init to OUT from the forms of FILES (in order)."
  (let ((n 0))
    (with-temp-file out
      (insert ";;; nemacs-init-wrapped --- generated by nemacs-wrap-init.el\n")
      (insert ";;; Do not edit; regenerated by the nemacs launcher.\n")
      (dolist (file files)
        (dolist (form (nemacs-wrap-init--forms file))
          (setq n (1+ n))
          (insert (format "(nemacs-init--begin %d %S)\n"
                          n (nemacs-wrap-init--hint form)))
          ;; the ok marker shares the form's top-level unit: when the
          ;; form hard-aborts on the reader, the marker is skipped too,
          ;; which is exactly what the report needs
          (insert "(progn\n")
          (prin1 (nemacs-wrap-init--lower form) (current-buffer))
          (insert (format "\n(nemacs-init--ok %d))\n" n)))))
    n))

(provide 'nemacs-wrap-init)

;;; nemacs-wrap-init.el ends here
