;;; nelisp-emacs-foundation-pkg.el --- package metadata -*- lexical-binding: t; no-byte-compile: t; -*-

;; Generated by scripts/nemacs-library-package-metadata.el.
;; Source of truth remains src/ and the package descriptor tooling.

(define-package
  "nelisp-emacs-foundation"
  "0.1.0"
  "Reusable nelisp-emacs compatibility primitives and core Lisp helpers."
  'nil
  :keywords '("emacs" "lisp" "nelisp" "compatibility" "fnd")
  :url "https://github.com/zawatton/nelisp-emacs"
  :maintainer "zawatton"
  :authors '("zawatton")
  :license "GPL-3.0-or-later")

;;; nelisp-emacs-foundation-pkg.el ends here
