;;; emacs-stub-bulk.el --- Auto-generated bulk stubs (extended pre-scan) -*- lexical-binding: t; -*-
;; Doc 51 Phase 3-A''-3 batch 4.  Generated from full symbol scan.
;; Each fn is no-op; vars are nil.
;;; Code:

(unless (fboundp 'abbreviate-file-name) (defun abbreviate-file-name (&rest _) nil))
(unless (fboundp 'abbrev-mode) (defun abbrev-mode (&rest _) nil))
(unless (fboundp 'abort-recursive-edit) (defun abort-recursive-edit (&rest _) nil))
(unless (fboundp 'add-function) (defun add-function (&rest _) nil))
(unless (fboundp 'add-text-properties) (defun add-text-properties (&rest _) nil))
(unless (boundp 'after-change-functions) (defvar after-change-functions nil))
(unless (boundp 'after-load-alist) (defvar after-load-alist nil))
(unless (fboundp 'all-completions) (defun all-completions (&rest _) nil))
(unless (fboundp 'append) (defun append (&rest _) nil))
(unless (fboundp 'apply) (defun apply (&rest _) nil))
(unless (fboundp 'aref) (defun aref (&rest _) nil))
(unless (fboundp 'arrayp) (defun arrayp (&rest _) nil))
(unless (fboundp 'aset) (defun aset (&rest _) nil))
(unless (fboundp 'ash) (defun ash (&rest _) nil))
(unless (fboundp 'assoc) (defun assoc (&rest _) nil))
(unless (fboundp 'assq) (defun assq (&rest _) nil))
(unless (fboundp 'atom) (defun atom (&rest _) nil))
(unless (fboundp 'auto-fill-mode) (defun auto-fill-mode (&rest _) nil))
(unless (fboundp 'autoload) (defun autoload (&rest _) nil))
(unless (fboundp 'autoload-do-load) (defun autoload-do-load (&rest _) nil))
(unless (boundp 'auto-mode-alist) (defvar auto-mode-alist nil))
(unless (fboundp 'auto-save-mode) (defun auto-save-mode (&rest _) nil))
(unless (fboundp 'backtrace) (defun backtrace (&rest _) nil))
(unless (fboundp 'backtrace-frame--internal) (defun backtrace-frame--internal (&rest _) nil))
(unless (fboundp 'backward-char) (defun backward-char (&rest _) nil))
(unless (fboundp 'backward-delete-char) (defun backward-delete-char (&rest _) nil))
(unless (fboundp 'backward-word) (defun backward-word (&rest _) nil))
(unless (fboundp 'beep) (defun beep (&rest _) nil))
(unless (boundp 'before-change-functions) (defvar before-change-functions nil))
(unless (fboundp 'beginning-of-line) (defun beginning-of-line (&rest _) nil))
(unless (fboundp 'bobp) (defun bobp (&rest _) nil))
(unless (fboundp 'bolp) (defun bolp (&rest _) nil))
(unless (fboundp 'bound-and-true-p) (defun bound-and-true-p (&rest _) nil))
(unless (fboundp 'boundp) (defun boundp (&rest _) nil))
(unless (fboundp 'bounds-of-thing-at-point) (defun bounds-of-thing-at-point (&rest _) nil))
(unless (fboundp 'buffer-file-name) (defun buffer-file-name (&rest _) nil))
(unless (boundp 'buffer-invisibility-spec) (defvar buffer-invisibility-spec nil))
(unless (fboundp 'buffer-list) (defun buffer-list (&rest _) nil))
(unless (boundp 'buffer-list-update-hook) (defvar buffer-list-update-hook nil))
(unless (fboundp 'buffer-live-p) (defun buffer-live-p (&rest _) nil))
(unless (fboundp 'buffer-local-value) (defun buffer-local-value (&rest _) nil))
(unless (fboundp 'buffer-modified-p) (defun buffer-modified-p (&rest _) nil))
(unless (fboundp 'buffer-name) (defun buffer-name (&rest _) nil))
(unless (boundp 'buffer-read-only) (defvar buffer-read-only nil))
(unless (fboundp 'buffer-size) (defun buffer-size (&rest _) nil))
(unless (fboundp 'buffer-string) (defun buffer-string (&rest _) nil))
(unless (fboundp 'buffer-substring) (defun buffer-substring (&rest _) nil))
(unless (fboundp 'buffer-substring-no-properties) (defun buffer-substring-no-properties (&rest _) nil))
(unless (boundp 'buffer-undo-list) (defvar buffer-undo-list nil))
(unless (fboundp 'byte-code) (defun byte-code (&rest _) nil))
(unless (fboundp 'byte-code-function-p) (defun byte-code-function-p (&rest _) nil))
(unless (fboundp 'byte-compile-warning-enabled-p) (defun byte-compile-warning-enabled-p (&rest _) nil))
(unless (fboundp 'call-interactively) (defun call-interactively (&rest _) nil))
(unless (fboundp 'call-process) (defun call-process (&rest _) nil))
(unless (fboundp 'call-process-region) (defun call-process-region (&rest _) nil))
(unless (fboundp 'cancel-timer) (defun cancel-timer (&rest _) nil))
(unless (fboundp 'capitalize-word) (defun capitalize-word (&rest _) nil))
(unless (fboundp 'car) (defun car (&rest _) nil))
(unless (fboundp 'car-safe) (defun car-safe (&rest _) nil))
(unless (boundp 'case-fold-search) (defvar case-fold-search nil))
(unless (fboundp 'cdr) (defun cdr (&rest _) nil))
(unless (fboundp 'cdr-safe) (defun cdr-safe (&rest _) nil))
(unless (fboundp 'ceiling) (defun ceiling (&rest _) nil))
(unless (fboundp 'char-after) (defun char-after (&rest _) nil))
(unless (fboundp 'char-before) (defun char-before (&rest _) nil))
(unless (fboundp 'char-syntax) (defun char-syntax (&rest _) nil))
(unless (fboundp 'char-table-p) (defun char-table-p (&rest _) nil))
(unless (fboundp 'char-to-string) (defun char-to-string (&rest _) nil))
(unless (fboundp 'chmod) (defun chmod (&rest _) nil))
(unless (fboundp 'combine-after-change-execute) (defun combine-after-change-execute (&rest _) nil))
(unless (boundp 'command-debug-status) (defvar command-debug-status nil))
(unless (boundp 'command-error-function) (defvar command-error-function nil))
(unless (fboundp 'commandp) (defun commandp (&rest _) nil))
(unless (fboundp 'command-remapping) (defun command-remapping (&rest _) nil))
(unless (fboundp 'compare-strings) (defun compare-strings (&rest _) nil))
(unless (fboundp 'compare-window-configurations) (defun compare-window-configurations (&rest _) nil))
(unless (fboundp 'comp-el-to-eln-rel-filename) (defun comp-el-to-eln-rel-filename (&rest _) nil))
(unless (boundp 'comp-enable-subr-trampolines) (defvar comp-enable-subr-trampolines nil))
(unless (fboundp 'completing-read) (defun completing-read (&rest _) nil))
(unless (fboundp 'compose-mail) (defun compose-mail (&rest _) nil))
(unless (fboundp 'concat) (defun concat (&rest _) nil))
(unless (fboundp 'cons) (defun cons (&rest _) nil))
(unless (fboundp 'consp) (defun consp (&rest _) nil))
(unless (fboundp 'copy-keymap) (defun copy-keymap (&rest _) nil))
(unless (fboundp 'copy-marker) (defun copy-marker (&rest _) nil))
(unless (fboundp 'copy-sequence) (defun copy-sequence (&rest _) nil))
(unless (fboundp 'ctl-x-4-prefix) (defun ctl-x-4-prefix (&rest _) nil))
(unless (fboundp 'ctl-x-5-prefix) (defun ctl-x-5-prefix (&rest _) nil))
(unless (fboundp 'current-buffer) (defun current-buffer (&rest _) nil))
(unless (fboundp 'current-case-table) (defun current-case-table (&rest _) nil))
(unless (fboundp 'current-global-map) (defun current-global-map (&rest _) nil))
(unless (boundp 'current-load-list) (defvar current-load-list nil))
(unless (fboundp 'current-local-map) (defun current-local-map (&rest _) nil))
(unless (fboundp 'current-message) (defun current-message (&rest _) nil))
(unless (boundp 'current-prefix-arg) (defvar current-prefix-arg nil))
(unless (fboundp 'current-window-configuration) (defun current-window-configuration (&rest _) nil))
(unless (boundp 'cursor-in-echo-area) (defvar cursor-in-echo-area nil))
(unless (fboundp 'cursor-intangible-mode) (defun cursor-intangible-mode (&rest _) nil))
(unless (fboundp 'cursor-sensor-mode) (defun cursor-sensor-mode (&rest _) nil))
(unless (boundp 'data-directory) (defvar data-directory nil))
(unless (fboundp 'debug) (defun debug (&rest _) nil))
(unless (boundp 'debugger) (defvar debugger nil))
(unless (boundp 'debug-ignored-errors) (defvar debug-ignored-errors nil))
(unless (boundp 'debug-on-error) (defvar debug-on-error nil))
(unless (fboundp 'decode-coding-string) (defun decode-coding-string (&rest _) nil))
(unless (fboundp 'defalias) (defun defalias (&rest _) nil))
(unless (fboundp 'default-boundp) (defun default-boundp (&rest _) nil))
(unless (boundp 'default-directory) (defvar default-directory nil))
(unless (fboundp 'default-file-modes) (defun default-file-modes (&rest _) nil))
(unless (fboundp 'default-value) (defun default-value (&rest _) nil))
(unless (fboundp 'define-derived-mode) (defun define-derived-mode (&rest _) nil))
(unless (fboundp 'define-key) (defun define-key (&rest _) nil))
(unless (fboundp 'define-minor-mode) (defun define-minor-mode (&rest _) nil))
(unless (fboundp 'define-obsolete-function-alias) (defun define-obsolete-function-alias (&rest _) nil))
(unless (fboundp 'define-obsolete-variable-alias) (defun define-obsolete-variable-alias (&rest _) nil))
(unless (fboundp 'defining-kbd-macro) (defun defining-kbd-macro (&rest _) nil))
(unless (fboundp 'defsubst) (defun defsubst (&rest _) nil))
(unless (boundp 'defun-declarations-alist) (defvar defun-declarations-alist nil))
(unless (fboundp 'defvaralias) (defun defvaralias (&rest _) nil))
(unless (boundp 'delayed-after-hook-functions) (defvar delayed-after-hook-functions nil))
(unless (boundp 'delayed-mode-hooks) (defvar delayed-mode-hooks nil))
(unless (boundp 'delayed-warnings-list) (defvar delayed-warnings-list nil))
(unless (fboundp 'delete) (defun delete (&rest _) nil))
(unless (fboundp 'delete-backward-char) (defun delete-backward-char (&rest _) nil))
(unless (fboundp 'delete-char) (defun delete-char (&rest _) nil))
(unless (fboundp 'delete-minibuffer-contents) (defun delete-minibuffer-contents (&rest _) nil))
(unless (fboundp 'delete-overlay) (defun delete-overlay (&rest _) nil))
(unless (fboundp 'delete-region) (defun delete-region (&rest _) nil))
(unless (fboundp 'delq) (defun delq (&rest _) nil))
(unless (fboundp 'describe-bindings) (defun describe-bindings (&rest _) nil))
(unless (fboundp 'describe-key) (defun describe-key (&rest _) nil))
(unless (fboundp 'digit-argument) (defun digit-argument (&rest _) nil))
(unless (fboundp 'ding) (defun ding (&rest _) nil))
(unless (fboundp 'directory-file-name) (defun directory-file-name (&rest _) nil))
(unless (fboundp 'discard-input) (defun discard-input (&rest _) nil))
(unless (fboundp 'display-buffer) (defun display-buffer (&rest _) nil))
(unless (fboundp 'display-graphic-p) (defun display-graphic-p (&rest _) nil))
(unless (fboundp 'display-popup-menus-p) (defun display-popup-menus-p (&rest _) nil))
(unless (fboundp 'display-warning) (defun display-warning (&rest _) nil))
(unless (fboundp 'documentation) (defun documentation (&rest _) nil))
(unless (fboundp 'downcase) (defun downcase (&rest _) nil))
(unless (fboundp 'downcase-region) (defun downcase-region (&rest _) nil))
(unless (fboundp 'downcase-word) (defun downcase-word (&rest _) nil))
(unless (fboundp 'drop) (defun drop (&rest _) nil))
(unless (boundp 'echo-keystrokes) (defvar echo-keystrokes nil))
(unless (fboundp 'elt) (defun elt (&rest _) nil))
(unless (fboundp 'emacs-pid) (defun emacs-pid (&rest _) nil))
(unless (fboundp 'emacs-version) (defun emacs-version (&rest _) nil))
(unless (boundp 'enable-recursive-minibuffers) (defvar enable-recursive-minibuffers nil))
(unless (fboundp 'encode-coding-string) (defun encode-coding-string (&rest _) nil))
(unless (fboundp 'end-of-line) (defun end-of-line (&rest _) nil))
(unless (fboundp 'eobp) (defun eobp (&rest _) nil))
(unless (fboundp 'eq) (defun eq (&rest _) nil))
(unless (fboundp 'eql) (defun eql (&rest _) nil))
(unless (fboundp 'equal) (defun equal (&rest _) nil))
(unless (fboundp 'erase-buffer) (defun erase-buffer (&rest _) nil))
(unless (fboundp 'error-message-string) (defun error-message-string (&rest _) nil))
(unless (fboundp 'eval) (defun eval (&rest _) nil))
(unless (fboundp 'event-convert-list) (defun event-convert-list (&rest _) nil))
(unless (fboundp 'exec-path) (defun exec-path (&rest _) nil))
(unless (fboundp 'execute-extended-command) (defun execute-extended-command (&rest _) nil))
(unless (fboundp 'execute-extended-command-for-buffer) (defun execute-extended-command-for-buffer (&rest _) nil))
(unless (boundp 'executing-kbd-macro) (defvar executing-kbd-macro nil))
(unless (fboundp 'exit-minibuffer) (defun exit-minibuffer (&rest _) nil))
(unless (fboundp 'exit-recursive-edit) (defun exit-recursive-edit (&rest _) nil))
(unless (fboundp 'exp) (defun exp (&rest _) nil))
(unless (fboundp 'expand-file-name) (defun expand-file-name (&rest _) nil))
(unless (fboundp 'fboundp) (defun fboundp (&rest _) nil))
(unless (fboundp 'featurep) (defun featurep (&rest _) nil))
(unless (boundp 'features) (defvar features nil))
(unless (fboundp 'fetch-bytecode) (defun fetch-bytecode (&rest _) nil))
(unless (fboundp 'field-beginning) (defun field-beginning (&rest _) nil))
(unless (fboundp 'field-end) (defun field-end (&rest _) nil))
(unless (fboundp 'file-exists-p) (defun file-exists-p (&rest _) nil))
(unless (fboundp 'file-name-absolute-p) (defun file-name-absolute-p (&rest _) nil))
(unless (fboundp 'file-name-extension) (defun file-name-extension (&rest _) nil))
(unless (fboundp 'file-name-nondirectory) (defun file-name-nondirectory (&rest _) nil))
(unless (fboundp 'file-name-sans-extension) (defun file-name-sans-extension (&rest _) nil))
(unless (fboundp 'file-newer-than-file-p) (defun file-newer-than-file-p (&rest _) nil))
(unless (fboundp 'file-truename) (defun file-truename (&rest _) nil))
(unless (boundp 'fill-column) (defvar fill-column nil))
(unless (fboundp 'fill-region) (defun fill-region (&rest _) nil))
(unless (boundp 'find-tag-default-function) (defvar find-tag-default-function nil))
(unless (boundp 'find-word-boundary-function-table) (defvar find-word-boundary-function-table nil))
(unless (fboundp 'flatten-list) (defun flatten-list (&rest _) nil))
(unless (fboundp 'float) (defun float (&rest _) nil))
(unless (fboundp 'floatp) (defun floatp (&rest _) nil))
(unless (fboundp 'float-time) (defun float-time (&rest _) nil))
(unless (boundp 'font-lock-defaults) (defvar font-lock-defaults nil))
(unless (fboundp 'force-mode-line-update) (defun force-mode-line-update (&rest _) nil))
(unless (fboundp 'format) (defun format (&rest _) nil))
(unless (fboundp 'format-message) (defun format-message (&rest _) nil))
(unless (fboundp 'format-prompt) (defun format-prompt (&rest _) nil))
(unless (fboundp 'format-spec) (defun format-spec (&rest _) nil))
(unless (fboundp 'forward-char) (defun forward-char (&rest _) nil))
(unless (fboundp 'forward-line) (defun forward-line (&rest _) nil))
(unless (fboundp 'forward-word) (defun forward-word (&rest _) nil))
(unless (fboundp 'frame-char-height) (defun frame-char-height (&rest _) nil))
(unless (fboundp 'frame-char-width) (defun frame-char-width (&rest _) nil))
(unless (fboundp 'frame-live-p) (defun frame-live-p (&rest _) nil))
(unless (fboundp 'framep) (defun framep (&rest _) nil))
(unless (fboundp 'frame-parameter) (defun frame-parameter (&rest _) nil))
(unless (fboundp 'frame-selected-window) (defun frame-selected-window (&rest _) nil))
(unless (fboundp 'frame-toggle-on-screen-keyboard) (defun frame-toggle-on-screen-keyboard (&rest _) nil))
(unless (fboundp 'fset) (defun fset (&rest _) nil))
(unless (fboundp 'funcall) (defun funcall (&rest _) nil))
(unless (fboundp 'funcall-interactively) (defun funcall-interactively (&rest _) nil))
(unless (fboundp 'funcall-with-delayed-message) (defun funcall-with-delayed-message (&rest _) nil))
(unless (boundp 'function-key-map) (defvar function-key-map nil))
(unless (fboundp 'functionp) (defun functionp (&rest _) nil))
(unless (fboundp 'fundamental-mode) (defun fundamental-mode (&rest _) nil))
(unless (fboundp 'garbage-collect) (defun garbage-collect (&rest _) nil))
(unless (fboundp 'generate-new-buffer-name) (defun generate-new-buffer-name (&rest _) nil))
(unless (fboundp 'get) (defun get (&rest _) nil))
(unless (fboundp 'get-buffer) (defun get-buffer (&rest _) nil))
(unless (fboundp 'get-buffer-create) (defun get-buffer-create (&rest _) nil))
(unless (fboundp 'get-buffer-process) (defun get-buffer-process (&rest _) nil))
(unless (fboundp 'get-char-property) (defun get-char-property (&rest _) nil))
(unless (fboundp 'getenv) (defun getenv (&rest _) nil))
(unless (fboundp 'gethash) (defun gethash (&rest _) nil))
(unless (fboundp 'get-load-suffixes) (defun get-load-suffixes (&rest _) nil))
(unless (fboundp 'get-text-property) (defun get-text-property (&rest _) nil))
(unless (fboundp 'gnus) (defun gnus (&rest _) nil))
(unless (fboundp 'goto-char) (defun goto-char (&rest _) nil))
(unless (fboundp 'gv-letplace) (defun gv-letplace (&rest _) nil))
(unless (fboundp 'hack-local-variables) (defun hack-local-variables (&rest _) nil))
(unless (fboundp 'handler-bind-1) (defun handler-bind-1 (&rest _) nil))
(unless (fboundp 'hash-table-p) (defun hash-table-p (&rest _) nil))
(unless (fboundp 'help) (defun help (&rest _) nil))
(unless (boundp 'help-char) (defvar help-char nil))
(unless (boundp 'help-form) (defvar help-form nil))
(unless (fboundp 'help-form-show) (defun help-form-show (&rest _) nil))
(unless (boundp 'history-delete-duplicates) (defvar history-delete-duplicates nil))
(unless (boundp 'history-length) (defvar history-length nil))
(unless (boundp 'horizontal-scroll-bar) (defvar horizontal-scroll-bar nil))
(unless (fboundp 'hs-minor-mode) (defun hs-minor-mode (&rest _) nil))
(unless (fboundp 'identity) (defun identity (&rest _) nil))
(unless (fboundp 'indent-to) (defun indent-to (&rest _) nil))
(unless (fboundp 'indent-to-column) (defun indent-to-column (&rest _) nil))
(unless (fboundp 'indirect-function) (defun indirect-function (&rest _) nil))
(unless (fboundp 'info) (defun info (&rest _) nil))
(unless (boundp 'inhibit-changing-match-data) (defvar inhibit-changing-match-data nil))
(unless (boundp 'inhibit-field-text-motion) (defvar inhibit-field-text-motion nil))
(unless (boundp 'inhibit-modification-hooks) (defvar inhibit-modification-hooks nil))
(unless (boundp 'inhibit-nul-byte-detection) (defvar inhibit-nul-byte-detection nil))
(unless (boundp 'inhibit-null-byte-detection) (defvar inhibit-null-byte-detection nil))
(unless (boundp 'inhibit-point-motion-hooks) (defvar inhibit-point-motion-hooks nil))
(unless (boundp 'inhibit-quit) (defvar inhibit-quit nil))
(unless (boundp 'inhibit-read-only) (defvar inhibit-read-only nil))
(unless (boundp 'input-decode-map) (defvar input-decode-map nil))
(unless (boundp 'input-method-function) (defvar input-method-function nil))
(unless (fboundp 'input-pending-p) (defun input-pending-p (&rest _) nil))
(unless (fboundp 'insert) (defun insert (&rest _) nil))
(unless (fboundp 'insert-buffer-substring) (defun insert-buffer-substring (&rest _) nil))
(unless (fboundp 'integerp) (defun integerp (&rest _) nil))
(unless (fboundp 'intern) (defun intern (&rest _) nil))
(unless (fboundp 'internal-event-symbol-parse-modifiers) (defun internal-event-symbol-parse-modifiers (&rest _) nil))
(unless (fboundp 'internal--labeled-narrow-to-region) (defun internal--labeled-narrow-to-region (&rest _) nil))
(unless (fboundp 'internal--labeled-widen) (defun internal--labeled-widen (&rest _) nil))
(unless (fboundp 'internal--track-mouse) (defun internal--track-mouse (&rest _) nil))
(unless (fboundp 'int-to-string) (defun int-to-string (&rest _) nil))
(unless (fboundp 'invocation-directory) (defun invocation-directory (&rest _) nil))
(unless (fboundp 'invocation-name) (defun invocation-name (&rest _) nil))
(unless (fboundp 'isearch-mode) (defun isearch-mode (&rest _) nil))
(unless (boundp 'jka-compr-load-suffixes) (defvar jka-compr-load-suffixes nil))
(unless (fboundp 'keyboard-coding-system) (defun keyboard-coding-system (&rest _) nil))
(unless (fboundp 'keyboard-quit) (defun keyboard-quit (&rest _) nil))
(unless (boundp 'keyboard-translate-table) (defvar keyboard-translate-table nil))
(unless (fboundp 'key-description) (defun key-description (&rest _) nil))
(unless (fboundp 'keymap-global-lookup) (defun keymap-global-lookup (&rest _) nil))
(unless (fboundp 'keymap-global-set) (defun keymap-global-set (&rest _) nil))
(unless (fboundp 'keymap-global-unset) (defun keymap-global-unset (&rest _) nil))
(unless (fboundp 'keymap-local-lookup) (defun keymap-local-lookup (&rest _) nil))
(unless (fboundp 'keymap-local-set) (defun keymap-local-set (&rest _) nil))
(unless (fboundp 'keymap-local-unset) (defun keymap-local-unset (&rest _) nil))
(unless (fboundp 'keymapp) (defun keymapp (&rest _) nil))
(unless (fboundp 'keymap-prompt) (defun keymap-prompt (&rest _) nil))
(unless (fboundp 'keymap-set-after) (defun keymap-set-after (&rest _) nil))
(unless (fboundp 'keymap-substitute) (defun keymap-substitute (&rest _) nil))
(unless (fboundp 'key-parse) (defun key-parse (&rest _) nil))
(unless (fboundp 'key-translate) (defun key-translate (&rest _) nil))
(unless (fboundp 'keywordp) (defun keywordp (&rest _) nil))
(unless (fboundp 'kill-all-local-variables) (defun kill-all-local-variables (&rest _) nil))
(unless (fboundp 'kill-buffer) (defun kill-buffer (&rest _) nil))
(unless (boundp 'kill-buffer-hook) (defvar kill-buffer-hook nil))
(unless (boundp 'kill-buffer-query-functions) (defvar kill-buffer-query-functions nil))
(unless (fboundp 'kill-emacs) (defun kill-emacs (&rest _) nil))
(unless (fboundp 'kill-local-variable) (defun kill-local-variable (&rest _) nil))
(unless (fboundp 'kmacro-end-macro) (defun kmacro-end-macro (&rest _) nil))
(unless (boundp 'last-command-event) (defvar last-command-event nil))
(unless (boundp 'last-input-event) (defvar last-input-event nil))
(unless (boundp 'last-nonmenu-event) (defvar last-nonmenu-event nil))
(unless (fboundp 'length) (defun length (&rest _) nil))
(unless (boundp 'lexical-binding) (defvar lexical-binding nil))
(unless (fboundp 'libxml-parse-html-region) (defun libxml-parse-html-region (&rest _) nil))
(unless (fboundp 'libxml-parse-xml-region) (defun libxml-parse-xml-region (&rest _) nil))
(unless (fboundp 'line-beginning-position) (defun line-beginning-position (&rest _) nil))
(unless (fboundp 'line-end-position) (defun line-end-position (&rest _) nil))
(unless (boundp 'line-spacing) (defvar line-spacing nil))
(unless (fboundp 'list) (defun list (&rest _) nil))
(unless (fboundp 'listp) (defun listp (&rest _) nil))
(unless (fboundp 'load) (defun load (&rest _) nil))
(unless (boundp 'load-dangerous-libraries) (defvar load-dangerous-libraries nil))
(unless (boundp 'load-file-name) (defvar load-file-name nil))
(unless (boundp 'load-file-rep-suffixes) (defvar load-file-rep-suffixes nil))
(unless (boundp 'load-history) (defvar load-history nil))
(unless (fboundp 'load-library) (defun load-library (&rest _) nil))
(unless (boundp 'load-path) (defvar load-path nil))
(unless (boundp 'load-suffixes) (defvar load-suffixes nil))
(unless (fboundp 'local-variable-if-set-p) (defun local-variable-if-set-p (&rest _) nil))
(unless (fboundp 'local-variable-p) (defun local-variable-p (&rest _) nil))
(unless (fboundp 'locate-file) (defun locate-file (&rest _) nil))
(unless (fboundp 'locate-file-internal) (defun locate-file-internal (&rest _) nil))
(unless (fboundp 'locate-user-emacs-file) (defun locate-user-emacs-file (&rest _) nil))
(unless (fboundp 'log) (defun log (&rest _) nil))
(unless (fboundp 'logand) (defun logand (&rest _) nil))
(unless (fboundp 'logior) (defun logior (&rest _) nil))
(unless (fboundp 'lognot) (defun lognot (&rest _) nil))
(unless (fboundp 'logxor) (defun logxor (&rest _) nil))
(unless (fboundp 'looking-at) (defun looking-at (&rest _) nil))
(unless (fboundp 'lookup-key) (defun lookup-key (&rest _) nil))
(unless (boundp 'macro-declarations-alist) (defvar macro-declarations-alist nil))
(unless (fboundp 'macroexpand-all) (defun macroexpand-all (&rest _) nil))
(unless (boundp 'macroexpand-all-environment) (defvar macroexpand-all-environment nil))
(unless (fboundp 'macroexp-compiling-p) (defun macroexp-compiling-p (&rest _) nil))
(unless (fboundp 'macroexp-const-p) (defun macroexp-const-p (&rest _) nil))
(unless (fboundp 'macroexp-copyable-p) (defun macroexp-copyable-p (&rest _) nil))
(unless (fboundp 'macroexp--fgrep) (defun macroexp--fgrep (&rest _) nil))
(unless (fboundp 'macroexp--funcall-if-compiled) (defun macroexp--funcall-if-compiled (&rest _) nil))
(unless (fboundp 'macroexp-let2) (defun macroexp-let2 (&rest _) nil))
(unless (fboundp 'macroexp-progn) (defun macroexp-progn (&rest _) nil))
(unless (fboundp 'macroexp-warn-and-return) (defun macroexp-warn-and-return (&rest _) nil))
(unless (boundp 'magic-fallback-mode-alist) (defvar magic-fallback-mode-alist nil))
(unless (fboundp 'mail) (defun mail (&rest _) nil))
(unless (boundp 'mail-user-agent) (defvar mail-user-agent nil))
(unless (boundp 'major-mode) (defvar major-mode nil))
(unless (boundp 'major-mode--suspended) (defvar major-mode--suspended nil))
(unless (fboundp 'make-char-table) (defun make-char-table (&rest _) nil))
(unless (fboundp 'make-directory) (defun make-directory (&rest _) nil))
(unless (fboundp 'make-directory-autoloads) (defun make-directory-autoloads (&rest _) nil))
(unless (fboundp 'make-frame-visible) (defun make-frame-visible (&rest _) nil))
(unless (fboundp 'make-hash-table) (defun make-hash-table (&rest _) nil))
(unless (fboundp 'make-keymap) (defun make-keymap (&rest _) nil))
(unless (fboundp 'make-local-variable) (defun make-local-variable (&rest _) nil))
(unless (fboundp 'make-obsolete) (defun make-obsolete (&rest _) nil))
(unless (fboundp 'make-obsolete-variable) (defun make-obsolete-variable (&rest _) nil))
(unless (fboundp 'make-overlay) (defun make-overlay (&rest _) nil))
(unless (fboundp 'make-process) (defun make-process (&rest _) nil))
(unless (fboundp 'make-sparse-keymap) (defun make-sparse-keymap (&rest _) nil))
(unless (fboundp 'make-string) (defun make-string (&rest _) nil))
(unless (fboundp 'make-symbol) (defun make-symbol (&rest _) nil))
(unless (fboundp 'make-variable-buffer-local) (defun make-variable-buffer-local (&rest _) nil))
(unless (fboundp 'make-vector) (defun make-vector (&rest _) nil))
(unless (fboundp 'mapatoms) (defun mapatoms (&rest _) nil))
(unless (fboundp 'mapbacktrace) (defun mapbacktrace (&rest _) nil))
(unless (fboundp 'mapc) (defun mapc (&rest _) nil))
(unless (fboundp 'mapcan) (defun mapcan (&rest _) nil))
(unless (fboundp 'mapcar) (defun mapcar (&rest _) nil))
(unless (fboundp 'mapconcat) (defun mapconcat (&rest _) nil))
(unless (fboundp 'map-keymap) (defun map-keymap (&rest _) nil))
(unless (fboundp 'mark) (defun mark (&rest _) nil))
(unless (fboundp 'markerp) (defun markerp (&rest _) nil))
(unless (fboundp 'marker-position) (defun marker-position (&rest _) nil))
(unless (fboundp 'match-beginning) (defun match-beginning (&rest _) nil))
(unless (fboundp 'match-data) (defun match-data (&rest _) nil))
(unless (fboundp 'match-data--translate) (defun match-data--translate (&rest _) nil))
(unless (fboundp 'match-end) (defun match-end (&rest _) nil))
(unless (fboundp 'max) (defun max (&rest _) nil))
(unless (boundp 'max-lisp-eval-depth) (defvar max-lisp-eval-depth nil))
(unless (fboundp 'member) (defun member (&rest _) nil))
(unless (fboundp 'memq) (defun memq (&rest _) nil))
(unless (fboundp 'memql) (defun memql (&rest _) nil))
(unless (boundp 'menu-prompting) (defvar menu-prompting nil))
(unless (fboundp 'message) (defun message (&rest _) nil))
(unless (boundp 'message-log-max) (defvar message-log-max nil))
(unless (boundp 'messages-buffer-max-lines) (defvar messages-buffer-max-lines nil))
(unless (fboundp 'min) (defun min (&rest _) nil))
(unless (boundp 'minibuffer-auto-raise) (defvar minibuffer-auto-raise nil))
(unless (boundp 'minibuffer-default-prompt-format) (defvar minibuffer-default-prompt-format nil))
(unless (boundp 'minibuffer-local-map) (defvar minibuffer-local-map nil))
(unless (fboundp 'minibuffer-message) (defun minibuffer-message (&rest _) nil))
(unless (fboundp 'minibufferp) (defun minibufferp (&rest _) nil))
(unless (fboundp 'minibuffer-prompt) (defun minibuffer-prompt (&rest _) nil))
(unless (fboundp 'minibuffer-prompt-end) (defun minibuffer-prompt-end (&rest _) nil))
(unless (fboundp 'minibuffer-recenter-top-bottom) (defun minibuffer-recenter-top-bottom (&rest _) nil))
(unless (fboundp 'minibuffer-scroll-down-command) (defun minibuffer-scroll-down-command (&rest _) nil))
(unless (fboundp 'minibuffer-scroll-other-window) (defun minibuffer-scroll-other-window (&rest _) nil))
(unless (fboundp 'minibuffer-scroll-other-window-down) (defun minibuffer-scroll-other-window-down (&rest _) nil))
(unless (fboundp 'minibuffer-scroll-up-command) (defun minibuffer-scroll-up-command (&rest _) nil))
(unless (boundp 'minibuffer-scroll-window) (defvar minibuffer-scroll-window nil))
(unless (fboundp 'minibuffer-window) (defun minibuffer-window (&rest _) nil))
(unless (fboundp 'minibuffer-with-setup-hook) (defun minibuffer-with-setup-hook (&rest _) nil))
(unless (boundp 'minor-mode-alist) (defvar minor-mode-alist nil))
(unless (boundp 'minor-mode-map-alist) (defvar minor-mode-map-alist nil))
(unless (fboundp 'mkdir) (defun mkdir (&rest _) nil))
(unless (fboundp 'mod) (defun mod (&rest _) nil))
(unless (boundp 'mode-line-mode-menu) (defvar mode-line-mode-menu nil))
(unless (boundp 'mode-name) (defvar mode-name nil))
(unless (boundp 'most-negative-fixnum) (defvar most-negative-fixnum nil))
(unless (boundp 'most-positive-fixnum) (defvar most-positive-fixnum nil))
(unless (fboundp 'move-marker) (defun move-marker (&rest _) nil))
(unless (fboundp 'move-overlay) (defun move-overlay (&rest _) nil))
(unless (fboundp 'multibyte-string-p) (defun multibyte-string-p (&rest _) nil))
(unless (fboundp 'mutex-lock) (defun mutex-lock (&rest _) nil))
(unless (fboundp 'mutex-unlock) (defun mutex-unlock (&rest _) nil))
(unless (fboundp 'narrow-to-region) (defun narrow-to-region (&rest _) nil))
(unless (fboundp 'native-comp-available-p) (defun native-comp-available-p (&rest _) nil))
(unless (boundp 'native-comp-deferred-compilation) (defvar native-comp-deferred-compilation nil))
(unless (boundp 'native-comp-enable-subr-trampolines) (defvar native-comp-enable-subr-trampolines nil))
(unless (fboundp 'native-comp-function-p) (defun native-comp-function-p (&rest _) nil))
(unless (boundp 'native-comp-jit-compilation) (defvar native-comp-jit-compilation nil))
(unless (fboundp 'native-comp-unit-file) (defun native-comp-unit-file (&rest _) nil))
(unless (fboundp 'natnump) (defun natnump (&rest _) nil))
(unless (fboundp 'nconc) (defun nconc (&rest _) nil))
(unless (boundp 'needed) (defvar needed nil))
(unless (fboundp 'negative-argument) (defun negative-argument (&rest _) nil))
(unless (fboundp 'newline) (defun newline (&rest _) nil))
(unless (fboundp 'next-property-change) (defun next-property-change (&rest _) nil))
(unless (fboundp 'next-single-property-change) (defun next-single-property-change (&rest _) nil))
(unless (fboundp 'nlistp) (defun nlistp (&rest _) nil))
(unless (boundp 'noninteractive) (defvar noninteractive nil))
(unless (fboundp 'normal-mode) (defun normal-mode (&rest _) nil))
(unless (fboundp 'nreverse) (defun nreverse (&rest _) nil))
(unless (fboundp 'nth) (defun nth (&rest _) nil))
(unless (fboundp 'nthcdr) (defun nthcdr (&rest _) nil))
(unless (fboundp 'null) (defun null (&rest _) nil))
(unless (fboundp 'number-at-point) (defun number-at-point (&rest _) nil))
(unless (fboundp 'numberp) (defun numberp (&rest _) nil))
(unless (fboundp 'number-to-string) (defun number-to-string (&rest _) nil))
(unless (boundp 'obarray) (defvar obarray nil))
(unless (fboundp 'object-intervals) (defun object-intervals (&rest _) nil))
(unless (fboundp 'occur) (defun occur (&rest _) nil))
(unless (boundp 'operating-system-release) (defvar operating-system-release nil))
(unless (fboundp 'other-frame) (defun other-frame (&rest _) nil))
(unless (boundp 'output) (defvar output nil))
(unless (fboundp 'overlay-buffer) (defun overlay-buffer (&rest _) nil))
(unless (fboundp 'overlay-end) (defun overlay-end (&rest _) nil))
(unless (fboundp 'overlay-get) (defun overlay-get (&rest _) nil))
(unless (fboundp 'overlay-properties) (defun overlay-properties (&rest _) nil))
(unless (fboundp 'overlay-put) (defun overlay-put (&rest _) nil))
(unless (fboundp 'overlay-recenter) (defun overlay-recenter (&rest _) nil))
(unless (fboundp 'overlays-in) (defun overlays-in (&rest _) nil))
(unless (fboundp 'overlay-start) (defun overlay-start (&rest _) nil))
(unless (boundp 'overriding-local-map) (defvar overriding-local-map nil))
(unless (boundp 'overriding-terminal-local-map) (defvar overriding-terminal-local-map nil))
(unless (fboundp 'overwrite-mode) (defun overwrite-mode (&rest _) nil))
(unless (boundp 'parse-sexp-lookup-properties) (defvar parse-sexp-lookup-properties nil))
(unless (fboundp 'pcase) (defun pcase (&rest _) nil))
(unless (fboundp 'pcase-dolist) (defun pcase-dolist (&rest _) nil))
(unless (boundp 'pending-undo-list) (defvar pending-undo-list nil))
(unless (fboundp 'play-sound-internal) (defun play-sound-internal (&rest _) nil))
(unless (fboundp 'plist-get) (defun plist-get (&rest _) nil))
(unless (fboundp 'plist-put) (defun plist-put (&rest _) nil))
(unless (fboundp 'point) (defun point (&rest _) nil))
(unless (fboundp 'point-at-bol) (defun point-at-bol (&rest _) nil))
(unless (fboundp 'point-at-eol) (defun point-at-eol (&rest _) nil))
(unless (fboundp 'point-max) (defun point-max (&rest _) nil))
(unless (fboundp 'point-min) (defun point-min (&rest _) nil))
(unless (fboundp 'pos-bol) (defun pos-bol (&rest _) nil))
(unless (fboundp 'pos-eol) (defun pos-eol (&rest _) nil))
(unless (fboundp 'posn-at-point) (defun posn-at-point (&rest _) nil))
(unless (boundp 'post-command-hook) (defvar post-command-hook nil))
(unless (boundp 'post-self-insert-hook) (defvar post-self-insert-hook nil))
(unless (boundp 'pre-command-hook) (defvar pre-command-hook nil))
(unless (boundp 'prefix-arg) (defvar prefix-arg nil))
(unless (fboundp 'prefix-numeric-value) (defun prefix-numeric-value (&rest _) nil))
(unless (fboundp 'primitive-undo) (defun primitive-undo (&rest _) nil))
(unless (fboundp 'prin1) (defun prin1 (&rest _) nil))
(unless (fboundp 'prin1-to-string) (defun prin1-to-string (&rest _) nil))
(unless (fboundp 'princ) (defun princ (&rest _) nil))
(unless (fboundp 'print) (defun print (&rest _) nil))
(unless (boundp 'print-unreadable-function) (defvar print-unreadable-function nil))
(unless (fboundp 'process-attributes) (defun process-attributes (&rest _) nil))
(unless (fboundp 'process-file) (defun process-file (&rest _) nil))
(unless (fboundp 'processp) (defun processp (&rest _) nil))
(unless (fboundp 'process-plist) (defun process-plist (&rest _) nil))
(unless (fboundp 'process-query-on-exit-flag) (defun process-query-on-exit-flag (&rest _) nil))
(unless (fboundp 'process-send-region) (defun process-send-region (&rest _) nil))
(unless (fboundp 'process-send-string) (defun process-send-string (&rest _) nil))
(unless (fboundp 'process-status) (defun process-status (&rest _) nil))
(unless (fboundp 'progress-reporter-make) (defun progress-reporter-make (&rest _) nil))
(unless (fboundp 'proper-list-p) (defun proper-list-p (&rest _) nil))
(unless (fboundp 'propertize) (defun propertize (&rest _) nil))
(unless (fboundp 'purecopy) (defun purecopy (&rest _) nil))
(unless (fboundp 'put) (defun put (&rest _) nil))
(unless (fboundp 'puthash) (defun puthash (&rest _) nil))
(unless (fboundp 'put-text-property) (defun put-text-property (&rest _) nil))
(unless (boundp 'query-replace-map) (defvar query-replace-map nil))
(unless (boundp 'quit-flag) (defvar quit-flag nil))
(unless (fboundp 'raise-frame) (defun raise-frame (&rest _) nil))
(unless (fboundp 'rassq) (defun rassq (&rest _) nil))
(unless (fboundp 'read) (defun read (&rest _) nil))
(unless (fboundp 'read-char) (defun read-char (&rest _) nil))
(unless (fboundp 'read-command) (defun read-command (&rest _) nil))
(unless (fboundp 'read-event) (defun read-event (&rest _) nil))
(unless (fboundp 'read-from-minibuffer) (defun read-from-minibuffer (&rest _) nil))
(unless (fboundp 'read-from-string) (defun read-from-string (&rest _) nil))
(unless (fboundp 'read-kbd-macro) (defun read-kbd-macro (&rest _) nil))
(unless (fboundp 'read-key-sequence) (defun read-key-sequence (&rest _) nil))
(unless (fboundp 'read-key-sequence-vector) (defun read-key-sequence-vector (&rest _) nil))
(unless (fboundp 'read-library-name) (defun read-library-name (&rest _) nil))
(unless (fboundp 'read-string) (defun read-string (&rest _) nil))
(unless (boundp 'real-this-command) (defvar real-this-command nil))
(unless (fboundp 'recenter) (defun recenter (&rest _) nil))
(unless (fboundp 'recenter-top-bottom) (defun recenter-top-bottom (&rest _) nil))
(unless (fboundp 'record) (defun record (&rest _) nil))
(unless (fboundp 'recordp) (defun recordp (&rest _) nil))
(unless (fboundp 'redirect-frame-focus) (defun redirect-frame-focus (&rest _) nil))
(unless (fboundp 'redisplay) (defun redisplay (&rest _) nil))
(unless (boundp 'redisplay-dont-pause) (defvar redisplay-dont-pause nil))
(unless (fboundp 'regexp-opt) (defun regexp-opt (&rest _) nil))
(unless (fboundp 'regexp-quote) (defun regexp-quote (&rest _) nil))
(unless (fboundp 'remember) (defun remember (&rest _) nil))
(unless (fboundp 'remove-list-of-text-properties) (defun remove-list-of-text-properties (&rest _) nil))
(unless (fboundp 'repeat) (defun repeat (&rest _) nil))
(unless (fboundp 'replace-match) (defun replace-match (&rest _) nil))
(unless (fboundp 're-search-backward) (defun re-search-backward (&rest _) nil))
(unless (fboundp 're-search-forward) (defun re-search-forward (&rest _) nil))
(unless (fboundp 'restore-buffer-modified-p) (defun restore-buffer-modified-p (&rest _) nil))
(unless (fboundp 'reverse) (defun reverse (&rest _) nil))
(unless (fboundp 'rplaca) (defun rplaca (&rest _) nil))
(unless (fboundp 'rplacd) (defun rplacd (&rest _) nil))
(unless (fboundp 'run-hooks) (defun run-hooks (&rest _) nil))
(unless (fboundp 'run-hook-with-args) (defun run-hook-with-args (&rest _) nil))
(unless (fboundp 'run-hook-with-args-until-success) (defun run-hook-with-args-until-success (&rest _) nil))
(unless (fboundp 'run-hook-wrapped) (defun run-hook-wrapped (&rest _) nil))
(unless (fboundp 'run-window-configuration-change-hook) (defun run-window-configuration-change-hook (&rest _) nil))
(unless (fboundp 'run-with-idle-timer) (defun run-with-idle-timer (&rest _) nil))
(unless (boundp 's) (defvar s nil))
(unless (fboundp 'safe-length) (defun safe-length (&rest _) nil))
(unless (fboundp 'save-current-buffer) (defun save-current-buffer (&rest _) nil))
(unless (fboundp 'save-excursion) (defun save-excursion (&rest _) nil))
(unless (fboundp 'save-restriction) (defun save-restriction (&rest _) nil))
(unless (fboundp 'scroll-bar-scale) (defun scroll-bar-scale (&rest _) nil))
(unless (fboundp 'scroll-down) (defun scroll-down (&rest _) nil))
(unless (fboundp 'scroll-down-command) (defun scroll-down-command (&rest _) nil))
(unless (fboundp 'scroll-left) (defun scroll-left (&rest _) nil))
(unless (fboundp 'scroll-other-window) (defun scroll-other-window (&rest _) nil))
(unless (fboundp 'scroll-other-window-down) (defun scroll-other-window-down (&rest _) nil))
(unless (fboundp 'scroll-right) (defun scroll-right (&rest _) nil))
(unless (fboundp 'scroll-up) (defun scroll-up (&rest _) nil))
(unless (fboundp 'scroll-up-command) (defun scroll-up-command (&rest _) nil))
(unless (fboundp 'search-backward-regexp) (defun search-backward-regexp (&rest _) nil))
(unless (fboundp 'search-forward) (defun search-forward (&rest _) nil))
(unless (fboundp 'search-forward-regexp) (defun search-forward-regexp (&rest _) nil))
(unless (fboundp 'secure-hash) (defun secure-hash (&rest _) nil))
(unless (fboundp 'selected-frame) (defun selected-frame (&rest _) nil))
(unless (fboundp 'selected-window) (defun selected-window (&rest _) nil))
(unless (fboundp 'select-frame) (defun select-frame (&rest _) nil))
(unless (fboundp 'select-window) (defun select-window (&rest _) nil))
(unless (fboundp 'self-insert-command) (defun self-insert-command (&rest _) nil))
(unless (fboundp 'send-region) (defun send-region (&rest _) nil))
(unless (fboundp 'send-string) (defun send-string (&rest _) nil))
(unless (fboundp 'seq-find) (defun seq-find (&rest _) nil))
(unless (fboundp 'seq-uniq) (defun seq-uniq (&rest _) nil))
(unless (fboundp 'set-advertised-calling-convention) (defun set-advertised-calling-convention (&rest _) nil))
(unless (fboundp 'set-buffer) (defun set-buffer (&rest _) nil))
(unless (fboundp 'set-buffer-modified-p) (defun set-buffer-modified-p (&rest _) nil))
(unless (fboundp 'setcar) (defun setcar (&rest _) nil))
(unless (fboundp 'set-case-table) (defun set-case-table (&rest _) nil))
(unless (fboundp 'setcdr) (defun setcdr (&rest _) nil))
(unless (fboundp 'set-char-table-parent) (defun set-char-table-parent (&rest _) nil))
(unless (fboundp 'set-default) (defun set-default (&rest _) nil))
(unless (fboundp 'set-default-file-modes) (defun set-default-file-modes (&rest _) nil))
(unless (fboundp 'setf) (defun setf (&rest _) nil))
(unless (fboundp 'set-file-modes) (defun set-file-modes (&rest _) nil))
(unless (fboundp 'set-frame-selected-window) (defun set-frame-selected-window (&rest _) nil))
(unless (fboundp 'set-keymap-parent) (defun set-keymap-parent (&rest _) nil))
(unless (fboundp 'set-marker) (defun set-marker (&rest _) nil))
(unless (fboundp 'set-match-data) (defun set-match-data (&rest _) nil))
(unless (fboundp 'set-process-plist) (defun set-process-plist (&rest _) nil))
(unless (fboundp 'set-syntax-table) (defun set-syntax-table (&rest _) nil))
(unless (fboundp 'set-temporary-overlay-map) (defun set-temporary-overlay-map (&rest _) nil))
(unless (fboundp 'set-text-conversion-style) (defun set-text-conversion-style (&rest _) nil))
(unless (fboundp 'set-text-properties) (defun set-text-properties (&rest _) nil))
(unless (boundp 'set-variable-value-history) (defvar set-variable-value-history nil))
(unless (fboundp 'set-window-configuration) (defun set-window-configuration (&rest _) nil))
(unless (fboundp 'set-window-hscroll) (defun set-window-hscroll (&rest _) nil))
(unless (fboundp 'set-window-point) (defun set-window-point (&rest _) nil))
(unless (fboundp 'set-window-start) (defun set-window-start (&rest _) nil))
(unless (fboundp 'shell) (defun shell (&rest _) nil))
(unless (boundp 'shell-command-switch) (defvar shell-command-switch nil))
(unless (boundp 'shell-file-name) (defvar shell-file-name nil))
(unless (fboundp 'signal) (defun signal (&rest _) nil))
(unless (fboundp 'single-key-description) (defun single-key-description (&rest _) nil))
(unless (fboundp 'skip-chars-backward) (defun skip-chars-backward (&rest _) nil))
(unless (fboundp 'skip-syntax-backward) (defun skip-syntax-backward (&rest _) nil))
(unless (fboundp 'skip-syntax-forward) (defun skip-syntax-forward (&rest _) nil))
(unless (fboundp 'sleep-for) (defun sleep-for (&rest _) nil))
(unless (fboundp 'sort) (defun sort (&rest _) nil))
(unless (fboundp 'special-variable-p) (defun special-variable-p (&rest _) nil))
(unless (boundp 'standard-output) (defvar standard-output nil))
(unless (fboundp 'standard-syntax-table) (defun standard-syntax-table (&rest _) nil))
(unless (fboundp 'start-file-process) (defun start-file-process (&rest _) nil))
(unless (fboundp 'store-match-data) (defun store-match-data (&rest _) nil))
(unless (fboundp 'string) (defun string (&rest _) nil))
(unless (fboundp 'string-as-multibyte) (defun string-as-multibyte (&rest _) nil))
(unless (fboundp 'string-as-unibyte) (defun string-as-unibyte (&rest _) nil))
(unless (fboundp 'string-equal) (defun string-equal (&rest _) nil))
(unless (fboundp 'string-lessp) (defun string-lessp (&rest _) nil))
(unless (fboundp 'string-make-multibyte) (defun string-make-multibyte (&rest _) nil))
(unless (fboundp 'string-make-unibyte) (defun string-make-unibyte (&rest _) nil))
(unless (fboundp 'string-match) (defun string-match (&rest _) nil))
(unless (fboundp 'stringp) (defun stringp (&rest _) nil))
(unless (fboundp 'string-search) (defun string-search (&rest _) nil))
(unless (fboundp 'string-split) (defun string-split (&rest _) nil))
(unless (fboundp 'string-to-multibyte) (defun string-to-multibyte (&rest _) nil))
(unless (fboundp 'string-to-number) (defun string-to-number (&rest _) nil))
(unless (fboundp 'string-to-unibyte) (defun string-to-unibyte (&rest _) nil))
(unless (fboundp 'subr-arity) (defun subr-arity (&rest _) nil))
(unless (fboundp 'subr-native-comp-unit) (defun subr-native-comp-unit (&rest _) nil))
(unless (fboundp 'subrp) (defun subrp (&rest _) nil))
(unless (fboundp 'substitute-command-keys) (defun substitute-command-keys (&rest _) nil))
(unless (fboundp 'substring) (defun substring (&rest _) nil))
(unless (fboundp 'substring-no-properties) (defun substring-no-properties (&rest _) nil))
(unless (fboundp 'suspend-emacs) (defun suspend-emacs (&rest _) nil))
(unless (fboundp 'switch-to-buffer) (defun switch-to-buffer (&rest _) nil))
(unless (fboundp 'sxhash) (defun sxhash (&rest _) nil))
(unless (fboundp 'sxhash-equal) (defun sxhash-equal (&rest _) nil))
(unless (boundp 'sym) (defvar sym nil))
(unless (fboundp 'symbol-function) (defun symbol-function (&rest _) nil))
(unless (fboundp 'symbol-name) (defun symbol-name (&rest _) nil))
(unless (fboundp 'symbolp) (defun symbolp (&rest _) nil))
(unless (fboundp 'symbol-plist) (defun symbol-plist (&rest _) nil))
(unless (fboundp 'symbol-value) (defun symbol-value (&rest _) nil))
(unless (fboundp 'syntax-ppss-flush-cache) (defun syntax-ppss-flush-cache (&rest _) nil))
(unless (fboundp 'syntax-propertize) (defun syntax-propertize (&rest _) nil))
(unless (boundp 'syntax-propertize-function) (defvar syntax-propertize-function nil))
(unless (fboundp 'syntax-table) (defun syntax-table (&rest _) nil))
(unless (boundp 'system-type) (defvar system-type nil))
(unless (fboundp 'take) (defun take (&rest _) nil))
(unless (fboundp 'temp-buffer-resize-mode) (defun temp-buffer-resize-mode (&rest _) nil))
(unless (boundp 'temp-buffer-show-function) (defvar temp-buffer-show-function nil))
(unless (fboundp 'temporary-file-directory) (defun temporary-file-directory (&rest _) nil))
(unless (boundp 'text-conversion-style) (defvar text-conversion-style nil))
(unless (fboundp 'text-properties-at) (defun text-properties-at (&rest _) nil))
(unless (boundp 'this-command) (defvar this-command nil))
(unless (fboundp 'this-command-keys) (defun this-command-keys (&rest _) nil))
(unless (fboundp 'this-command-keys-vector) (defun this-command-keys-vector (&rest _) nil))
(unless (fboundp 'this-single-command-keys) (defun this-single-command-keys (&rest _) nil))
(unless (fboundp 'this-single-command-raw-keys) (defun this-single-command-raw-keys (&rest _) nil))
(unless (boundp 'throw-on-input) (defvar throw-on-input nil))
(unless (fboundp 'time-convert) (defun time-convert (&rest _) nil))
(unless (fboundp 'time-less-p) (defun time-less-p (&rest _) nil))
(unless (fboundp 'top-level) (defun top-level (&rest _) nil))
(unless (boundp 'translation-table-for-input) (defvar translation-table-for-input nil))
(unless (fboundp 'truncate) (defun truncate (&rest _) nil))
(unless (fboundp 'tty-top-frame) (defun tty-top-frame (&rest _) nil))
(unless (fboundp 'undo) (defun undo (&rest _) nil))
(unless (fboundp 'undo-amalgamate-change-group) (defun undo-amalgamate-change-group (&rest _) nil))
(unless (fboundp 'undo-auto-amalgamate) (defun undo-auto-amalgamate (&rest _) nil))
(unless (fboundp 'undo-boundary) (defun undo-boundary (&rest _) nil))
(unless (boundp 'undo-in-progress) (defvar undo-in-progress nil))
(unless (boundp 'undo-limit) (defvar undo-limit nil))
(unless (fboundp 'undo-more) (defun undo-more (&rest _) nil))
(unless (boundp 'undo-outer-limit) (defvar undo-outer-limit nil))
(unless (boundp 'undo-strong-limit) (defvar undo-strong-limit nil))
(unless (fboundp 'unhandled-file-name-directory) (defun unhandled-file-name-directory (&rest _) nil))
(unless (fboundp 'unintern) (defun unintern (&rest _) nil))
(unless (boundp 'unread-command-events) (defvar unread-command-events nil))
(unless (fboundp 'upcase-region) (defun upcase-region (&rest _) nil))
(unless (fboundp 'upcase-word) (defun upcase-word (&rest _) nil))
(unless (fboundp 'update-directory-autoloads) (defun update-directory-autoloads (&rest _) nil))
(unless (boundp 'use-dialog-box) (defvar use-dialog-box nil))
(unless (fboundp 'use-global-map) (defun use-global-map (&rest _) nil))
(unless (fboundp 'use-local-map) (defun use-local-map (&rest _) nil))
(unless (fboundp 'user-login-name) (defun user-login-name (&rest _) nil))
(unless (fboundp 'user-original-login-name) (defun user-original-login-name (&rest _) nil))
(unless (boundp 'values) (defvar values nil))
(unless (fboundp 'variable-at-point) (defun variable-at-point (&rest _) nil))
(unless (fboundp 'vconcat) (defun vconcat (&rest _) nil))
(unless (fboundp 'vector) (defun vector (&rest _) nil))
(unless (fboundp 'vectorp) (defun vectorp (&rest _) nil))
(unless (boundp 'vertical-scroll-bar) (defvar vertical-scroll-bar nil))
(unless (fboundp 'view-mode) (defun view-mode (&rest _) nil))
(unless (fboundp 'warn) (defun warn (&rest _) nil))
(unless (fboundp 'wholenump) (defun wholenump (&rest _) nil))
(unless (fboundp 'widen) (defun widen (&rest _) nil))
(unless (fboundp 'window-buffer) (defun window-buffer (&rest _) nil))
(unless (fboundp 'window-combination-limit) (defun window-combination-limit (&rest _) nil))
(unless (fboundp 'window-configuration-equal-p) (defun window-configuration-equal-p (&rest _) nil))
(unless (fboundp 'window-end) (defun window-end (&rest _) nil))
(unless (fboundp 'window-font-height) (defun window-font-height (&rest _) nil))
(unless (fboundp 'window-font-width) (defun window-font-width (&rest _) nil))
(unless (fboundp 'window-frame) (defun window-frame (&rest _) nil))
(unless (fboundp 'window-height) (defun window-height (&rest _) nil))
(unless (fboundp 'window-live-p) (defun window-live-p (&rest _) nil))
(unless (fboundp 'windowp) (defun windowp (&rest _) nil))
(unless (fboundp 'window-point) (defun window-point (&rest _) nil))
(unless (fboundp 'window-system) (defun window-system (&rest _) nil))
(unless (fboundp 'window-width) (defun window-width (&rest _) nil))
(unless (fboundp 'with-connection-local-variables) (defun with-connection-local-variables (&rest _) nil))
(unless (fboundp 'with-suppressed-warnings) (defun with-suppressed-warnings (&rest _) nil))
(unless (fboundp 'with-temp-buffer-window) (defun with-temp-buffer-window (&rest _) nil))
(unless (fboundp 'write-region) (defun write-region (&rest _) nil))
(unless (boundp 'x-gtk-use-window-move) (defvar x-gtk-use-window-move nil))
(unless (fboundp 'x-popup-dialog) (defun x-popup-dialog (&rest _) nil))
(unless (fboundp 'xterm-mouse-mode) (defun xterm-mouse-mode (&rest _) nil))
(unless (fboundp 'yank) (defun yank (&rest _) nil))
(unless (boundp 'yank-transform-functions) (defvar yank-transform-functions nil))
(unless (fboundp 'yes-or-no-p) (defun yes-or-no-p (&rest _) nil))
(unless (fboundp 'y-or-n-p-with-timeout) (defun y-or-n-p-with-timeout (&rest _) nil))
(unless (fboundp 'zlib-available-p) (defun zlib-available-p (&rest _) nil))

(provide 'emacs-stub-bulk)
;;; emacs-stub-bulk.el ends here
