;;; iso-transl.el --- lightweight ISO input translations  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 zawatton + Claude

;; This file is part of nelisp-emacs.

;;; Commentary:

;; A compact compatibility facade for GNU Emacs' `iso-transl.el'.  The
;; full upstream file is a large static translation table.  This module
;; keeps the standard public variables and commands available for the
;; daily-driver path, while covering the common Latin-1, punctuation, and
;; symbol mnemonics used by tests and early vendor loads.

;;; Code:

(require 'emacs-keymap-builtins)

(defconst iso-transl--alt-modifier-mask 4194304
  "Integer modifier bit used by Emacs for Alt-key translations.")

(defvar key-translation-map nil
  "Key translation map used by standalone NeLisp when Emacs has not set one.")

(defvar isearch-mode-map nil
  "Isearch keymap placeholder for standalone NeLisp.")

(defvar iso-transl-dead-key-alist
  '((?' . mute-acute)
    (?` . mute-grave)
    (?\" . mute-diaeresis)
    (?^ . mute-asciicircum)
    (?~ . mute-asciitilde)
    (?' . dead-acute)
    (?` . dead-grave)
    (?\" . dead-diaeresis)
    (?^ . dead-asciicircum)
    (?~ . dead-asciitilde)
    (?^ . dead-circum)
    (?^ . dead-circumflex)
    (?~ . dead-tilde))
  "Mapping of ASCII accent characters to dead-key symbols.")

(defvar iso-transl-char-map
  '(("* " . [#x00a0])
    (" " . [#x00a0])
    ("*!" . [#x00a1])
    ("!" . [#x00a1])
    ("\"\"" . [#x00a8])
    ("\"A" . [#x00c4])
    ("\"E" . [#x00cb])
    ("\"I" . [#x00cf])
    ("\"O" . [#x00d6])
    ("\"U" . [#x00dc])
    ("\"a" . [#x00e4])
    ("\"e" . [#x00eb])
    ("\"i" . [#x00ef])
    ("\"o" . [#x00f6])
    ("\"s" . [#x00df])
    ("\"u" . [#x00fc])
    ("\"y" . [#x00ff])
    ("''" . [#x00b4])
    ("'A" . [#x00c1])
    ("'E" . [#x00c9])
    ("'I" . [#x00cd])
    ("'O" . [#x00d3])
    ("'U" . [#x00da])
    ("'Y" . [#x00dd])
    ("'a" . [#x00e1])
    ("'e" . [#x00e9])
    ("'i" . [#x00ed])
    ("'o" . [#x00f3])
    ("'u" . [#x00fa])
    ("'y" . [#x00fd])
    ("*$" . [#x00a4])
    ("$" . [#x00a4])
    ("*+" . [#x00b1])
    ("+" . [#x00b1])
    (",," . [#x00b8])
    (",C" . [#x00c7])
    (",c" . [#x00e7])
    ("*-" . [#x00ad])
    ("-" . [#x00ad])
    ("*." . [#x00b7])
    (".." . [#x00b7])
    ("//" . [#x00f7])
    ("/A" . [#x00c5])
    ("/E" . [#x00c6])
    ("/O" . [#x00d8])
    ("/a" . [#x00e5])
    ("/e" . [#x00e6])
    ("/o" . [#x00f8])
    ("1/2" . [#x00bd])
    ("1/4" . [#x00bc])
    ("3/4" . [#x00be])
    ("*<" . [#x00ab])
    ("<" . [#x00ab])
    ("*=" . [#x00af])
    ("==" . [#x00af])
    ("*>" . [#x00bb])
    (">" . [#x00bb])
    ("*?" . [#x00bf])
    ("?" . [#x00bf])
    ("*C" . [#x00a9])
    ("C" . [#x00a9])
    ("*E" . [#x20ac])
    ("E" . [#x20ac])
    ("*L" . [#x00a3])
    ("L" . [#x00a3])
    ("*P" . [#x00b6])
    ("P" . [#x00b6])
    ("*R" . [#x00ae])
    ("R" . [#x00ae])
    ("*S" . [#x00a7])
    ("S" . [#x00a7])
    ("*T" . [#x2122])
    ("T" . [#x2122])
    ("*Y" . [#x00a5])
    ("Y" . [#x00a5])
    ("^1" . [#x00b9])
    ("^2" . [#x00b2])
    ("^3" . [#x00b3])
    ("^A" . [#x00c2])
    ("^E" . [#x00ca])
    ("^I" . [#x00ce])
    ("^O" . [#x00d4])
    ("^U" . [#x00db])
    ("^a" . [#x00e2])
    ("^e" . [#x00ea])
    ("^i" . [#x00ee])
    ("^o" . [#x00f4])
    ("^u" . [#x00fb])
    ("_a" . [#x00aa])
    ("_o" . [#x00ba])
    ("`A" . [#x00c0])
    ("`E" . [#x00c8])
    ("`I" . [#x00cc])
    ("`O" . [#x00d2])
    ("`U" . [#x00d9])
    ("`a" . [#x00e0])
    ("`e" . [#x00e8])
    ("`i" . [#x00ec])
    ("`o" . [#x00f2])
    ("`u" . [#x00f9])
    ("*c" . [#x00a2])
    ("c" . [#x00a2])
    ("*o" . [#x00b0])
    ("o" . [#x00b0])
    ("OE" . [#x0152])
    ("Oe" . [#x0153])
    ("*u" . [#x00b5])
    ("u" . [#x00b5])
    ("*m" . [#x00b5])
    ("m" . [#x00b5])
    ("*x" . [#x00d7])
    ("x" . [#x00d7])
    ("*|" . [#x00a6])
    ("|" . [#x00a6])
    ("~A" . [#x00c3])
    ("~D" . [#x00d0])
    ("~N" . [#x00d1])
    ("~O" . [#x00d5])
    ("~T" . [#x00de])
    ("~a" . [#x00e3])
    ("~d" . [#x00f0])
    ("~n" . [#x00f1])
    ("~o" . [#x00f5])
    ("~t" . [#x00fe])
    ("~~" . [#x00ac])
    ("[" . [#x2018])
    ("]" . [#x2019])
    ("{" . [#x201c])
    ("}" . [#x201d])
    ("1+" . [#x2020])
    ("2+" . [#x2021])
    ("**" . [#x2022])
    ("*'" . [#x2032])
    ("*\"" . [#x2033])
    ("No" . [#x2116])
    ("a<" . [#x2190])
    ("a>" . [#x2192])
    ("a=" . [#x2194])
    ("ae" . [#x00e6])
    ("AE" . [#x00c6])
    ("_-" . [#x2212])
    ("~=" . [#x2248])
    ("/=" . [#x2260])
    ("_<" . [#x2264])
    ("_>" . [#x2265])
    ("' " . "'")
    ("` " . "`")
    ("\" " . "\"")
    ("^ " . "^")
    ("~ " . "~"))
  "Alist of character translations for entering ISO characters.")

(defvar iso-transl-language-alist
  '(("Esperanto"
     ("C" . [#x0108])
     ("G" . [#x011c])
     ("H" . [#x0124])
     ("J" . [#x0134])
     ("S" . [#x015c])
     ("U" . [#x016c])
     ("c" . [#x0109])
     ("g" . [#x011d])
     ("h" . [#x0125])
     ("j" . [#x0135])
     ("s" . [#x015d])
     ("u" . [#x016d]))
    ("French"
     ("C" . [#x00c7])
     ("c" . [#x00e7])
     ("~<" . [#x2039])
     ("~>" . [#x203a]))
    ("German"
     ("A" . [#x00c4])
     ("O" . [#x00d6])
     ("S" . [#x1e9e])
     ("U" . [#x00dc])
     ("a" . [#x00e4])
     ("o" . [#x00f6])
     ("s" . [#x00df])
     ("u" . [#x00fc]))
    ("Portuguese"
     ("C" . [#x00c7])
     ("c" . [#x00e7]))
    ("Spanish"
     ("!" . [#x00a1])
     ("?" . [#x00bf])
     ("N" . [#x00d1])
     ("n" . [#x00f1])))
  "Language-specific shorter translation lists for `C-x 8'.")

(defvar iso-transl-ctl-x-8-map nil
  "Keymap for the `C-x 8' ISO translation prefix.")

(defun iso-transl--ensure-keymaps ()
  "Ensure the keymaps used by this lightweight facade exist."
  (unless iso-transl-ctl-x-8-map
    (setq iso-transl-ctl-x-8-map (make-sparse-keymap))
    (fset 'iso-transl-ctl-x-8-map iso-transl-ctl-x-8-map))
  (unless key-translation-map
    (setq key-translation-map (make-sparse-keymap)))
  (define-key key-translation-map "\C-x8" iso-transl-ctl-x-8-map))

(defun iso-transl--define-isearch-dead-key (key)
  "Clear KEY in `isearch-mode-map' when that map is available."
  (when (and isearch-mode-map (keymapp isearch-mode-map))
    (define-key isearch-mode-map key nil)))

(defun iso-transl--define-alt-and-dead-keys (key translated-vec)
  "Install Alt and dead-key translations for KEY to TRANSLATED-VEC."
  (let ((inchar (aref key 0))
        (vec (vconcat key)))
    (aset vec 0 (logior (aref vec 0) iso-transl--alt-modifier-mask))
    (define-key key-translation-map vec translated-vec)
    (iso-transl--define-isearch-dead-key (vector (aref vec 0)))
    (dolist (entry iso-transl-dead-key-alist)
      (when (eq (car entry) inchar)
        (let ((deadvec (copy-sequence vec))
              (deadkey (cdr entry)))
          (aset deadvec 0 deadkey)
          (define-key key-translation-map deadvec translated-vec)
          (iso-transl--define-isearch-dead-key (vector deadkey)))))))

(defun iso-transl-define-keys (alist)
  "Install ISO translations from ALIST.
Each entry is (KEY . TRANSLATION), matching GNU Emacs'
`iso-transl-char-map' shape."
  (iso-transl--ensure-keymaps)
  (dolist (entry alist)
    (let ((key (car entry))
          (translated-vec (cdr entry)))
      (define-key iso-transl-ctl-x-8-map key translated-vec)
      (iso-transl--define-alt-and-dead-keys key translated-vec))))

(defun iso-transl-set-language (lang)
  "Set shorter key bindings for characters relevant for LANG."
  (interactive
   (list (let ((completion-ignore-case t))
           (completing-read "Set which language? "
                            iso-transl-language-alist nil t))))
  (let ((entry (assoc lang iso-transl-language-alist)))
    (unless entry
      (error "Unknown iso-transl language: %s" lang))
    (iso-transl-define-keys (cdr entry))))

(iso-transl-define-keys iso-transl-char-map)

(provide 'iso-transl)

;;; iso-transl.el ends here
