;;; nelisp-emacs.el --- Reusable nelisp-emacs library facade  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 zawatton + Claude

;; This file is part of nelisp-emacs.

;;; Commentary:

;; Public library entry point for consumers that want the reusable
;; nelisp-emacs C-core replacement surface without loading the
;; application/bootstrap policy in `emacs-init'.  Optional app features
;; such as TUI realization and editor-heavy lazy features remain behind
;; the `emacs-init-load-*' functions.

;;; Code:

(defconst nelisp-emacs-library-contract-version 1
  "Version of the external `nelisp-emacs' library consumer contract.")

(defconst nelisp-emacs-library-features
  '(emacs-foundation
    emacs-text-core
    emacs-buffer-core
    emacs-editing
    emacs-io
    emacs-special-buffers
    emacs-core
    emacs-textmodes-stub)
  "Reusable feature groups loaded by the `nelisp-emacs' facade.
This manifest is intentionally limited to library-owned surfaces.
Application bootstrap, concrete TUI/GUI frontends, and editor-heavy lazy
features remain behind `emacs-init' and its explicit loader functions.")

(dolist (feature nelisp-emacs-library-features)
  (require feature))

(defconst nelisp-emacs-library-packages
  `((foundation
     :owner FND
     :feature emacs-foundation
     :features ,emacs-foundation-features
     :lazy-features nil)
    (text-core
     :owner TXT
     :feature emacs-text-core
     :features ,emacs-text-core-features
     :lazy-features (nelisp-coding-jis-tables))
    (buffer-core
     :owner BUF
     :feature emacs-buffer-core
     :features ,emacs-buffer-core-features
     :lazy-features (emacs-bookmark-ui
                     emacs-buffer-ui
                     emacs-isearch
                     emacs-replace))
    (editing
     :owner BUF
     :feature emacs-editing
     :features ,emacs-editing-features
     :lazy-features nil)
    (io
     :owner IO
     :feature emacs-io
     :features ,emacs-io-features
     :lazy-features (emacs-dump
                     image-loader
                     nemacs-loaddefs
                     emacs-dired-min
                     files-standalone-buffer
                     emacs-shell-command
                     emacs-project))
    (special-buffers
     :owner BUF
     :feature emacs-special-buffers
     :features (emacs-special-buffers)
     :lazy-features nil)
    (core
     :owner CORE
     :feature emacs-core
     :features ,emacs-core-features
     :lazy-features (emacs-elisp-eval
                     emacs-elisp-mode
                     emacs-font-lock
                     emacs-ielm
                     lisp-mode
                     emacs-redisplay-core
                     emacs-syntax-table
                     emacs-tui-backend
                     emacs-tui-event
                     emacs-tui-terminfo))
    (textmodes-stub
     :owner FEAT
     :feature emacs-textmodes-stub
     :features (emacs-textmodes-stub)
     :lazy-features nil))
  "Reusable package groups exposed by the `nelisp-emacs' facade.
Each entry is `(NAME :owner OWNER :feature FEATURE :features FEATURES
:lazy-features LAZY-FEATURES)'.  OWNER matches the primary Doc 18
  ownership group.  FEATURE is the facade feature for that package group.
FEATURES is the eager load membership for that group.  LAZY-FEATURES are
package-owned companion features that stay out of facade eager loads.")

(defconst nelisp-emacs-library-stable-package-api
  '((foundation
     :owner FND
     :package-id nelisp-emacs-foundation
     :symbols ((function emacs-callproc-populate-process-environment)
               (function emacs-callproc-getenv)
               (function emacs-char-table-p)
               (function emacs-char-table-ascii-vector)
               (function emacs-char-table-ref)
               (function emacs-char-table-set)
               (function emacs-char-table-set-range)
               (function emacs-char-table-range)
               (function emacs-char-table-parent)
               (function emacs-char-table-set-parent)
               (function emacs-char-table-subtype)
               (function emacs-char-table-extra-slot)
               (function emacs-char-table-set-extra-slot)
               (function emacs-char-table-map)
               (function emacs-char-table-copy)
               (function emacs-char-table-max-char)
               (function emacs-char-table-make)
               (function emacs-os-sysname->system-type)
               (function emacs-detect-system-type)
               (function emacs-os-detect-and-set!)
               (function emacs-os-apply-os-polyfills!)
               (function emacs-os-detect-and-set-dirs!)
               (function emacs-uname)
               (function emacs-display-window-system)
               (function emacs-display-graphic-p)
               (function emacs-display-color-p)
               (function emacs-display-multi-frame-p)
               (variable emacs-os-uname-syscall-number)))
    (text-core
     :owner TXT
     :package-id nelisp-emacs-text-core
     :symbols ((function nelisp-rx-compile)
               (function nelisp-rx-string-match)
               (function nelisp-rx-string-match-all)
               (function nelisp-rx-replace)
               (function nelisp-rx-replace-all)
               (variable nelisp-coding-utf8-bom-emit-on-write)
               (variable nelisp-coding-error-strategy)
               (variable nelisp-coding-latin1-replacement-codepoint)
               (variable nelisp-coding-utf8-bom)
               (variable nelisp-coding-utf8-replacement-char)
               (variable nelisp-coding-utf8-max-codepoint)
               (variable nelisp-coding-utf8-surrogate-min)
               (variable nelisp-coding-utf8-surrogate-max)
               (variable nelisp-coding-latin1-max-codepoint)
               (function nelisp-coding-utf8-decode)
               (function nelisp-coding-utf8-encode)
               (function nelisp-coding-utf8-encode-string)
               (function nelisp-coding-latin1-decode)
               (function nelisp-coding-latin1-encode)
               (function nelisp-coding-latin1-encode-string)
               (function nelisp-coding-jis-tables-verify-hash)
               (function nelisp-coding-jis-tables-rebuild)
               (function nelisp-coding-shift-jis-decode)
               (function nelisp-coding-shift-jis-encode)
               (function nelisp-coding-shift-jis-encode-string)
               (function nelisp-coding-euc-jp-decode)
               (function nelisp-coding-euc-jp-encode)
               (function nelisp-coding-euc-jp-encode-string)
               (variable nelisp-coding-stream-default-chunk-size)
               (function nelisp-coding-stream-state-create)
               (function nelisp-coding-stream-decode-chunk)
               (function nelisp-coding-stream-decode-finalize)
               (function nelisp-coding-stream-encode-chunk)
               (function nelisp-coding-stream-encode-finalize)
               (function nelisp-coding-read-file-with-encoding)
               (function nelisp-coding-write-file-with-encoding)))
    (buffer-core
     :owner BUF
     :package-id nelisp-emacs-buffer-core
     :symbols ((function nelisp-ec-generate-new-buffer)
               (function nelisp-ec-current-buffer)
               (function nelisp-ec-set-buffer)
               (macro nelisp-ec-with-current-buffer)
               (function nelisp-ec-kill-buffer)
               (function nelisp-ec-point)
               (function nelisp-ec-point-min)
               (function nelisp-ec-point-max)
               (function nelisp-ec-goto-char)
               (function nelisp-ec-buffer-size)
               (function nelisp-ec-forward-char)
               (function nelisp-ec-backward-char)
               (function nelisp-ec-insert)
               (function nelisp-ec-insert-char-code-fast)
               (function nelisp-ec-delete-region)
               (function nelisp-ec-delete-char)
               (function nelisp-ec-erase-buffer)
               (function nelisp-ec-buffer-substring)
               (function nelisp-ec-buffer-string)
               (macro nelisp-ec-save-excursion)
               (macro nelisp-ec-save-restriction)
               (macro nelisp-ec-save-current-buffer)
               (function nelisp-ec-narrow-to-region)
               (function nelisp-ec-widen)
               (function nelisp-ec-make-marker)
               (function nelisp-ec-set-marker)
               (function nelisp-ec-marker-position)
               (function nelisp-ec-marker-buffer)
               (function nelisp-ec-marker-insertion-type)
               (function nelisp-ec-set-marker-insertion-type)
               (function nelisp-ec-point-marker)
               (function nelisp-ec-search-forward)
               (function nelisp-ec-search-backward)
               (function nelisp-ec-looking-at-p)
               (function nelisp-ec-re-search-forward)
               (function nelisp-ec-re-search-backward)
               (function nelisp-ec-looking-at)
               (function nelisp-ec-match-data)
               (function nelisp-ec-match-beginning)
               (function nelisp-ec-match-end)
               (function emacs-buffer-current)
               (function emacs-buffer-buffer-list)
               (function emacs-buffer-buffers-by-mode)
               (function emacs-buffer-generate-new-buffer-name)
               (function emacs-buffer-make-local-variable)
               (function emacs-buffer-make-variable-buffer-local)
               (function emacs-buffer-buffer-local-variables)
               (function emacs-buffer-buffer-local-value)
               (function emacs-buffer-set-buffer-local-value)
               (function emacs-buffer-local-variable-p)
               (function emacs-buffer-local-variable-if-set-p)
               (function emacs-buffer-default-value)
               (function emacs-buffer-default-boundp)
               (function emacs-buffer-set-default)
               (macro emacs-buffer-setq-default)
               (function emacs-buffer-kill-local-variable)
               (function emacs-buffer-kill-all-local-variables)
               (function emacs-buffer-buffer-undo-list)
               (function emacs-buffer-buffer-disable-undo)
               (function emacs-buffer-buffer-enable-undo)
               (function emacs-buffer-undo-boundary)
               (function emacs-buffer-record-insertion)
               (function emacs-buffer-record-deletion)
               (function emacs-buffer-undo)
               (macro emacs-buffer-modify-without-undo)
               (function emacs-buffer-buffer-modified-p)
               (function emacs-buffer-set-buffer-modified-p)
               (function emacs-buffer-restore-buffer-modified-p)
               (function emacs-buffer-toggle-read-only-direct)
               (function emacs-buffer-buffer-chars-modified-tick)
               (function emacs-buffer-buffer-text-tick)
               (function emacs-buffer-bump-modified-tick)
               (function emacs-buffer-clone-indirect-buffer)
               (function emacs-buffer-buffer-base-buffer)
               (function make-text-buffer)
               (function text-buffer-insert-char-code)
               (function text-buffer-insert)
               (function text-buffer-delete)
               (function text-buffer-cursor)
               (function text-buffer-set-cursor)
               (function text-buffer-substring)
               (function text-buffer-search)
               (function text-buffer-length)
               (function text-buffer-multibyte-p)
               (function text-buffer-byte-length)
               (function emacs-buffer-put-text-property)
               (function emacs-buffer-add-text-properties)
               (function emacs-buffer-remove-text-properties)
               (function emacs-buffer-set-text-properties)
               (function emacs-buffer-get-text-property)
               (function emacs-buffer-text-property-at)
               (function emacs-buffer-text-property-view)
               (function emacs-buffer-next-property-change)
               (function emacs-buffer-previous-property-change)
               (function emacs-buffer-next-single-property-change)
               (function emacs-buffer-previous-single-property-change)
               (function emacs-buffer-get-char-property)
               (function emacs-buffer-overlayp)
               (function emacs-buffer-make-overlay)
               (function emacs-buffer-overlay-start)
               (function emacs-buffer-overlay-end)
               (function emacs-buffer-overlay-buffer)
               (function emacs-buffer-overlay-properties)
               (function emacs-buffer-overlay-put)
               (function emacs-buffer-overlay-get)
               (function emacs-buffer-move-overlay)
               (function emacs-buffer-delete-overlay)
               (function emacs-buffer-delete-all-overlays)
               (function emacs-buffer-overlays-at)
               (function emacs-buffer-overlays-in)
               (function emacs-buffer-overlay-lists)
               (function emacs-buffer-copy-overlay)))
    (editing
     :owner BUF
     :package-id nelisp-emacs-editing
     :symbols ((function emacs-undo-buffer-undo-list)
               (function emacs-undo-set-buffer-undo-list)
               (function emacs-undo-disabled-p)
               (function emacs-undo-reset)
               (function emacs-undo-undo-boundary)
               (function emacs-undo-record-insert)
               (function emacs-undo-record-delete)
               (function emacs-undo-primitive-undo)
               (function emacs-undo-undo)
               (function emacs-undo-undo-direct)
               (function emacs-undo-run-command)
               (function emacs-edit-self-insert-direct)
               (function emacs-edit-delete-backward-direct)
               (function emacs-edit-run-quoted-insert-command)
               (function emacs-edit-copy-region-direct)
               (function emacs-edit-kill-region-direct)
               (function emacs-edit-kill-line-direct)
               (function emacs-edit-kill-whole-line-direct)
               (function emacs-edit-delete-region-direct)
               (function emacs-edit-transform-region-direct)
               (function emacs-edit-run-transform-region-command)
               (function emacs-edit-toggle-line-comment-direct)
               (function emacs-edit-comment-dwim-direct)
               (function emacs-edit-yank-direct)
               (function emacs-edit-yank-pop-direct)
               (function emacs-edit-yank-pop-result-direct)
               (function emacs-edit-run-yank-pop-command)
               (function emacs-edit-set-mark-direct)
               (function emacs-edit-region-bounds-direct)
               (function emacs-edit-shift-selection-plan)
               (function emacs-edit-mouse-drag-region-plan)
               (function emacs-edit-mark-whole-buffer-direct)
               (function emacs-edit-exchange-point-and-mark-direct)
               (function emacs-edit-goto-position-direct)
               (function emacs-edit-select-word-at-direct)
               (function emacs-edit-run-select-word-at-command)
               (function emacs-edit-select-line-at-direct)
               (function emacs-edit-run-select-line-at-command)
               (function emacs-edit-page-scroll-direct)
               (function emacs-edit-forward-paragraph-direct)
               (function emacs-edit-backward-paragraph-direct)
               (function emacs-edit-mark-paragraph-direct)
               (function emacs-edit-run-mark-paragraph-command)
               (function emacs-edit-goto-buffer-boundary-direct)
               (function emacs-edit-forward-word-position)
               (function emacs-edit-kill-word-direct)
               (function emacs-edit-matching-paren-position-direct)
               (function emacs-edit-forward-sexp-direct)
               (function emacs-edit-backward-sexp-direct)
               (function emacs-edit-kill-sexp-direct)
               (function emacs-edit-forward-sentence-direct)
               (function emacs-edit-backward-sentence-direct)
               (function emacs-edit-kill-sentence-direct)
               (function emacs-edit-backward-kill-sentence-direct)
               (function emacs-edit-transpose-chars-direct)
               (function emacs-edit-delete-horizontal-space-direct)
               (function emacs-edit-just-one-space-direct)
               (function emacs-edit-delete-indentation-direct)
               (function emacs-edit-zap-to-char-direct)
               (function emacs-edit-sort-lines-direct)
               (function emacs-edit-delete-blank-lines-direct)
               (function emacs-edit-delete-trailing-whitespace-direct)
               (function emacs-edit-fill-paragraph-direct)
               (function emacs-edit-run-fill-paragraph-command)
               (function emacs-edit-count-words-in-range)
               (function emacs-edit-count-lines-in-range)
               (function emacs-edit-count-range)
               (function emacs-edit-dabbrev-word-at-point-prefix)
               (function emacs-edit-dabbrev-find-completion)
               (function emacs-edit-dabbrev-expand-direct)
               (function emacs-edit-tab-to-tab-stop-direct)
               (function emacs-edit-register-value)
               (function emacs-edit-copy-to-register-direct)
               (function emacs-edit-insert-register-direct)
               (function emacs-edit-point-to-register-direct)
               (function emacs-edit-jump-to-register-target)
               (function emacs-edit-goto-register-position-direct)))
    (io
     :owner IO
     :package-id nelisp-emacs-io
     :symbols ((function emacs-process-delegate)
               (function emacs-process-call-process)
               (function emacs-process-call-process-region)
               (function emacs-process-start-process)
               (function emacs-process-make-process)
               (function emacs-process-processp)
               (function emacs-process-process-list)
               (function emacs-process-process-status)
               (function emacs-process-process-exit-status)
               (function emacs-process-process-buffer)
               (function emacs-process-process-name)
               (function emacs-process-process-command)
               (function emacs-process-process-live-p)
               (function emacs-process-process-id)
               (function emacs-process-process-mark)
               (function emacs-process-set-process-filter)
               (function emacs-process-set-process-sentinel)
               (function emacs-process-accept-process-output)
               (function emacs-process-signal-process)
               (function emacs-process-kill-process)
               (function emacs-process-process-send-string)
               (function emacs-process-process-send-eof)
               (function emacs-process-delete-process)
               (function emacs-process-shell-command)
               (function emacs-process-shell-command-to-string)
               (variable emacs-process-shell-file-name)
               (variable emacs-process-shell-command-switch)
               (variable emacs-standalone-version)
               (variable emacs-standalone-force-mode)
               (function emacs-standalone-mode-p)
               (function emacs-standalone-active-p)
               (function emacs-standalone-register-primitive)
               (function emacs-standalone-unregister-primitive)
               (function emacs-standalone-has-primitive-p)
               (function emacs-standalone-registered-primitives)
               (function emacs-standalone-clear-registry)
               (function emacs-standalone-call-primitive)
               (function emacs-standalone-dispatch)
               (function emacs-standalone-init)
               (function emacs-standalone-uninit)
               (function emacs-standalone-status)
               (function nelisp-ec-access)
               (function nelisp-ec-file-name-absolute-p)
               (function nelisp-ec-substitute-in-file-name)
               (function nelisp-ec-file-name-directory)
               (function nelisp-ec-file-name-nondirectory)
               (function nelisp-ec-file-name-sans-extension)
               (function nelisp-ec-file-name-as-directory)
               (function nelisp-ec-expand-file-name)
               (function nelisp-ec-file-exists-p)
               (function nelisp-ec-file-readable-p)
               (function nelisp-ec-file-directory-p)
               (function nelisp-ec-file-attributes)
               (function nelisp-ec-directory-files)
               (function nelisp-ec-make-directory)
               (function nelisp-ec-delete-file)
               (function nelisp-ec-rename-file)
               (function nelisp-ec-file-executable-p)
               (function nelisp-ec-executable-find)
               (function nelisp-ec-insert-file-contents)
               (function nelisp-ec-write-region)))
    (special-buffers
     :owner BUF
     :package-id nelisp-emacs-special-buffers
     :symbols ((variable emacs-special-buffers-scratch-name)
               (variable emacs-special-buffers-messages-name)
               (variable emacs-special-buffers-warnings-name)
               (variable emacs-special-buffers-scratch-initial-message)
               (variable emacs-special-buffers-backend)
               (function emacs-special-buffers-register-backend)
               (function emacs-special-buffers-special-buffer-p)
               (function emacs-special-buffers-default-text)
               (function emacs-special-buffers-read-only-p)
               (function emacs-special-buffers-ensure-buffer)
               (function emacs-special-buffers-ensure-standard-buffers)
               (function emacs-special-buffers-display-plan)
               (function emacs-special-buffers-append-to-buffer)
               (function emacs-special-buffers-switch-to-buffer)
               (function emacs-special-buffers-message)
               (function emacs-special-buffers-display-warning)
               (function emacs-special-buffers-lwarn)
               (function emacs-special-buffers-warn)))
    (core
     :owner CORE
     :package-id nelisp-emacs-core
     :symbols ((function emacs-mode-major-mode)
               (function emacs-mode-mode-name)
               (function emacs-mode-set-major-mode)
               (function emacs-mode-reset)
               (function emacs-mode-run-mode-hooks)
               (function emacs-mode-kill-all-local-variables)
               (function emacs-mode-fundamental-mode)
               (function emacs-mode-text-mode)
               (function emacs-mode-emacs-lisp-mode)
               (macro emacs-mode-define-derived-mode)
               (function emacs-mode-auto-mode-alist)
               (function emacs-mode-set-auto-mode-alist)
               (function emacs-mode-set-auto-mode)
               (variable emacs-mode-fundamental-mode-hook)
               (variable emacs-mode-text-mode-hook)
               (variable emacs-mode-emacs-lisp-mode-hook)
               (function emacs-faces-facep)
               (function emacs-faces-make-face)
               (function emacs-faces-attribute)
               (function emacs-faces-set-attribute)
               (function emacs-faces-foreground)
               (function emacs-faces-background)
               (function emacs-faces-set-foreground)
               (function emacs-faces-set-background)
               (function emacs-faces-list)
               (macro emacs-faces-defface)
               (function emacs-faces-reset)
               (function emacs-frame-reset)
               (function emacs-frame-set-backend-dispatch)
               (function emacs-frame-current-backend)
               (function emacs-frame-capability-p)
               (function emacs-frame-framep)
               (function emacs-frame-frame-live-p)
               (function emacs-frame-selected-frame)
               (function emacs-frame-frame-list)
               (function emacs-frame-window-frame)
               (function emacs-frame-make-frame)
               (function emacs-frame-delete-frame)
               (function emacs-frame-delete-other-frames)
               (function emacs-frame-frame-width)
               (function emacs-frame-frame-height)
               (function emacs-frame-frame-char-width)
               (function emacs-frame-frame-char-height)
               (function emacs-frame-frame-pixel-width)
               (function emacs-frame-frame-pixel-height)
               (function emacs-frame-set-frame-size)
               (function emacs-frame-set-frame-position)
               (function emacs-frame-frame-parameters)
               (function emacs-frame-frame-parameter)
               (function emacs-frame-set-frame-parameter)
               (function emacs-frame-modify-frame-parameters)
               (function emacs-frame-frame-visible-p)
               (function emacs-frame-make-frame-visible)
               (function emacs-frame-make-frame-invisible)
               (function emacs-frame-raise-frame)
               (function emacs-frame-lower-frame)
               (function emacs-frame-select-frame)
               (function emacs-frame-frame-focus)
               (function emacs-frame-frame-windows)
               (function emacs-frame-display-pixel-width)
               (function emacs-frame-display-pixel-height)
               (function emacs-frame-use-tui-backend)
               (function emacs-frame-use-stub-backend)
               (function emacs-frame-tui-handle)
               (function emacs-frame-tui-event-handle)
               (function emacs-frame-tui-info)
               (variable emacs-frame-tui-resize-hook)
               (variable emacs-frame-tui-read-event-timeout-ms)
               (variable emacs-frame-tui-key-hook)
               (function emacs-window-reset)
               (function emacs-window-windowp)
               (function emacs-window-selected-window)
               (function emacs-window-get-window)
               (function emacs-window-window-buffer)
               (function emacs-window-window-frame)
               (function emacs-window-window-list)
               (function emacs-window-window-list-1)
               (function emacs-window-next-window)
               (function emacs-window-previous-window)
               (function emacs-window-get-buffer-window)
               (function emacs-window-get-buffer-window-list)
               (function emacs-window-split-window)
               (function emacs-window-split-window-vertically)
               (function emacs-window-split-window-horizontally)
               (function emacs-window-one-window-p)
               (function emacs-window-delete-window)
               (function emacs-window-delete-other-windows)
               (function emacs-window-delete-windows-on)
               (function emacs-window-balance-windows)
               (function emacs-window-window-width)
               (function emacs-window-window-height)
               (function emacs-window-window-pixel-width)
               (function emacs-window-window-pixel-height)
               (function emacs-window-window-start)
               (function emacs-window-window-end)
               (function emacs-window-window-point)
               (function emacs-window-window-edges)
               (function emacs-window-window-resizable)
               (function emacs-window-set-window-buffer)
               (function emacs-window-set-window-point)
               (function emacs-window-set-window-start)
               (function emacs-window-window-parameter)
               (function emacs-window-set-window-parameter)
               (function emacs-window-current-window-configuration)
               (function emacs-window-set-window-configuration)
               (function emacs-window-other-window-impl)
               (function emacs-window-select-window)
               (macro emacs-window-save-selected-window)
               (macro emacs-window-with-selected-window)
               (function emacs-window-split-window-below)
               (function emacs-window-split-window-right)
               (function emacs-window-window-live-p)
               (function emacs-window-window-valid-p)
               (function emacs-window-frame-selected-window)
               (function emacs-window-other-window)
               (function emacs-window-enlarge-window)
               (function emacs-window-shrink-window)
               (function emacs-window-display-buffer)
               (function emacs-window-pop-to-buffer)
               (function emacs-window-quit-window)
               (function emacs-keymap-key-parse)
               (function emacs-keymap-key-valid-p)
               (function emacs-keymap-keymap-set)
               (function emacs-keymap-keymap-lookup)
               (function emacs-keymap-keymap-unset)
               (function emacs-keymap-keymap-global-set)
               (function emacs-keymap-keymap-local-set)
               (function emacs-keymap-keymap-global-unset)
               (function emacs-keymap-keymap-local-unset)
               (function emacs-keymap-make-sparse-keymap)
               (function emacs-keymap-make-keymap)
               (function emacs-keymap-keymapp)
               (function emacs-keymap-copy-keymap)
               (function emacs-keymap-define-key)
               (function emacs-keymap-full-slot)
               (function emacs-keymap-direct-slot-vector)
               (function emacs-keymap-define-key-fast)
               (function emacs-keymap-make-compatible-full-keymap)
               (function emacs-keymap-build-single-key-cache)
               (function emacs-keymap-install-overriding-terminal-map)
               (function emacs-keymap-clear-overriding-terminal-map)
               (function emacs-keymap-define-key-after)
               (function emacs-keymap-lookup-with-parent)
               (function emacs-keymap-lookup-key)
               (function emacs-keymap-keymap-parent)
               (function emacs-keymap-set-keymap-parent)
               (function emacs-keymap-keymap-prompt)
               (function emacs-keymap-current-global-map)
               (function emacs-keymap-use-global-map)
               (function emacs-keymap-current-local-map)
               (function emacs-keymap-use-local-map)
               (function emacs-keymap-chain-at)
               (function emacs-keymap-key-binding)
               (function emacs-keymap-map-keymap)
               (function emacs-keymap-where-is-internal)
               (function emacs-keymap-substitute-key-definition)
               (function emacs-keymap-key-description)
               (function emacs-keymap-this-command-keys)
               (function emacs-keymap-this-command-keys-vector)
               (function emacs-keymap-read-key-sequence)
               (variable emacs-keymap-chain-overlay-provider)
               (variable emacs-keymap-chain-textprop-provider)
               (variable emacs-keymap-global-map)
               (variable emacs-keymap-overriding-local-map)
               (variable emacs-keymap-overriding-terminal-local-map)
               (variable emacs-keymap-minor-mode-overriding-map-alist)
               (variable emacs-keymap-minor-mode-map-alist)
               (variable emacs-keymap-emulation-mode-map-alists)
               (variable emacs-keymap-contract-version)
               (variable emacs-keymap-chain-inject-contract-version)
               (variable emacs-keymap-chain-with-textprop)
               (variable emacs-minibuffer-prompt-properties)
               (variable emacs-minibuffer-default-history-symbol)
               (variable emacs-minibuffer-message-timeout)
               (variable emacs-minibuffer-completion-ignore-case)
               (variable emacs-minibuffer-history)
               (variable emacs-minibuffer-default)
               (variable emacs-minibuffer-gui-backend)
               (variable emacs-minibuffer-gui-standard-backend-keys)
               (variable emacs-minibuffer-gui-purpose)
               (variable emacs-minibuffer-gui-prompt)
               (variable emacs-minibuffer-gui-history-symbol)
               (variable emacs-minibuffer-gui-completion-table)
               (variable emacs-minibuffer-gui-collection)
               (variable emacs-minibuffer-gui-initial-input)
               (variable emacs-minibuffer-gui-require-match)
               (function emacs-minibuffer-gui-register-backend)
               (function emacs-minibuffer-gui-standard-backend)
               (function emacs-minibuffer-gui-register-standard-backend)
               (function emacs-minibuffer-gui-backend-call)
               (function emacs-minibuffer-gui-refresh-context-from-backend)
               (function emacs-minibuffer-gui-history-symbol-for-purpose)
               (variable emacs-minibuffer-gui-read-purpose-names)
               (function emacs-minibuffer-gui-purpose-uses-read-p)
               (function emacs-minibuffer-gui-keymap-entry)
               (function emacs-minibuffer-gui-start-from-keymap)
               (function emacs-minibuffer-gui-start-spec-from-keymaps)
               (function emacs-minibuffer-gui-start-spec)
               (variable emacs-minibuffer-gui-extended-command-followup-alist)
               (function emacs-minibuffer-gui-extended-command-followup)
               (function emacs-minibuffer-gui-extended-command-commit-spec)
               (variable emacs-minibuffer-gui-replace-followup-alist)
               (function emacs-minibuffer-gui-replace-followup)
               (variable emacs-minibuffer-gui-replace-commit-command-alist)
               (function emacs-minibuffer-gui-replace-commit-command)
               (function emacs-minibuffer-gui-replace-from-store-state)
               (function emacs-minibuffer-gui-replace-from-clear-state)
               (function emacs-minibuffer-gui-command-commit-spec)
               (function emacs-minibuffer-gui-finish-followup)
               (function emacs-minibuffer-gui-execute-command-spec)
               (function emacs-minibuffer-gui-finish-read)
               (function emacs-minibuffer-gui-collection-lines)
               (function emacs-minibuffer-gui-candidate-source-kind)
               (function emacs-minibuffer-gui-filter-candidate-lines)
               (function emacs-minibuffer-gui-candidates-for-purpose)
               (function emacs-minibuffer-gui-filtered-candidates-for-purpose)
               (function emacs-minibuffer-gui-candidate-refresh-state)
               (function emacs-minibuffer-gui-completion-candidates)
               (function emacs-minibuffer-gui-longest-common-prefix)
               (function emacs-minibuffer-gui-candidate-suffix)
               (function emacs-minibuffer-gui-tab-completion-plan)
               (function emacs-minibuffer-gui-key-plan)
               (function emacs-minibuffer-gui-text-delete-backward-state)
               (function emacs-minibuffer-gui-text-insert-state)
               (function emacs-minibuffer-gui-complete-first-line-state)
               (function emacs-minibuffer-gui-session-begin-state)
               (function emacs-minibuffer-gui-session-initial-input-state)
               (function emacs-minibuffer-gui-session-commit-state)
               (function emacs-minibuffer-gui-enter-state)
               (function emacs-minibuffer-gui-exit-state)
               (function emacs-minibuffer-gui-begin-read)
               (function emacs-minibuffer-gui-set-initial-input)
               (function emacs-minibuffer-gui-commit-read)
               (function emacs-minibuffer-gui-complete)
               (variable emacs-minibuffer-gui-abort-key-names)
               (function emacs-minibuffer-gui-abort-key-p)
               (function emacs-minibuffer-gui-maybe-start-from-keymap)
               (function emacs-minibuffer-gui-maybe-start-from-keymaps)
               (function emacs-minibuffer-gui-start-current-context)
               (function emacs-minibuffer-gui-maybe-start-current-context)
               (function emacs-minibuffer-gui-handle-key)
               (function emacs-minibuffer-gui-handle-key-current-context)
               (function emacs-minibuffer-gui-read-from-minibuffer)
               (function emacs-minibuffer-gui-completing-read)
               (function emacs-minibuffer-gui-start-purpose-read)
               (function emacs-minibuffer-read-from-minibuffer)
               (function emacs-minibuffer-read-string)
               (function emacs-minibuffer-read-no-blanks-input)
               (function emacs-minibuffer-read-key)
               (function emacs-minibuffer-read-buffer)
               (function emacs-minibuffer-read-file-name)
               (function emacs-minibuffer-read-directory-name)
               (function emacs-minibuffer-read-passwd)
               (function emacs-minibuffer-read-number)
               (function emacs-minibuffer-y-or-n-p)
               (function emacs-minibuffer-yes-or-no-p)
               (function emacs-minibuffer-completing-read)
               (function emacs-minibuffer-try-completion)
               (function emacs-minibuffer-all-completions)
               (function emacs-minibuffer-test-completion)
               (function emacs-minibuffer-minibufferp)
               (function emacs-minibuffer-active-minibuffer-window)
               (function emacs-minibuffer-minibuffer-window)
               (function emacs-minibuffer-minibuffer-prompt)
               (function emacs-minibuffer-minibuffer-contents)
               (function emacs-minibuffer-minibuffer-prompt-end)
               (function emacs-minibuffer-minibuffer-prompt-width)
               (function emacs-minibuffer-exit-minibuffer)
               (function emacs-minibuffer-abort-recursive-edit)
               (function emacs-minibuffer-minibuffer-message)
               (function emacs-minibuffer-feed-input)
               (function emacs-minibuffer-reset)
               (variable emacs-command-loop-gui-backend)
               (variable emacs-command-loop-gui-command)
               (variable emacs-command-loop-gui-effective-command)
               (variable emacs-command-loop-gui-keys)
               (variable emacs-command-loop-gui-arg)
               (variable emacs-command-loop-gui-status)
               (variable emacs-command-loop-gui-prefix-arg)
               (function emacs-command-loop-reset)
               (function emacs-command-loop-gui-register-backend)
               (function emacs-command-loop-gui-refresh-context-from-backend)
               (function emacs-command-loop-gui-keymap-command)
               (function emacs-command-loop-gui-lookup-key-sequence-from-sources)
               (function emacs-command-loop-gui-set-context)
               (function emacs-command-loop-gui-command-execution-state)
               (function emacs-command-loop-gui-replace-execution-state)
               (function emacs-command-loop-gui-ingest-request-context)
               (variable emacs-command-loop-gui-benign-status-command-names)
               (function emacs-command-loop-gui-finalize-status)
               (function emacs-command-loop-gui-finalize-status-current-context)
               (function emacs-command-loop-gui-writeback-command-name)
               (function emacs-command-loop-gui-writeback-command-name-current-context)
               (function emacs-command-loop-gui-write-post-command-state)
               (function emacs-command-loop-gui-write-post-command-state-current-context)
               (function emacs-command-loop-gui-lane-writeback-spec)
               (function emacs-command-loop-gui-writeback-spec-flag)
               (function emacs-command-loop-gui-write-lane-state)
               (function emacs-command-loop-gui-apply-post-command-writeback)
               (function emacs-command-loop-gui-before-command)
               (function emacs-command-loop-gui-self-insert-key-text)
               (function emacs-command-loop-gui-minibuffer-active-p)
               (function emacs-command-loop-gui-minibuffer-key)
               (function emacs-command-loop-gui-minibuffer-initial-input)
               (function emacs-command-loop-gui-finish-command)
               (function emacs-command-loop-gui-minibuffer-handle-key)
               (function emacs-command-loop-gui-maybe-start-minibuffer)
               (function emacs-command-loop-gui-call-interactively)
               (function emacs-command-loop-gui-call-interactively-context)
               (function emacs-command-loop-gui-call-interactively-current-context)
               (function emacs-command-loop-gui-command-execute-call)
               (function emacs-command-loop-gui-command-execute)
               (function emacs-command-loop-gui-command-execute-context)
               (function emacs-command-loop-gui-command-execute-current-context)
               (function emacs-command-loop-gui-execute-extended-command)
               (function emacs-command-loop-gui-execute-extended-command-current-context)
               (function emacs-command-loop-gui-project-command)
               (function emacs-command-loop-gui-project-command-current-context)
               (variable emacs-command-loop-gui-undo-save-command-names)
               (function emacs-command-loop-gui-undo-save-command-p)
               (function emacs-command-loop-gui-save-undo-if-needed)
               (function emacs-command-loop-gui-key-dispatch-spec)
               (function emacs-command-loop-gui-dispatch-key-sequence)
               (function emacs-command-loop-gui-dispatch-context)
               (function emacs-command-loop-gui-dispatch-current-context)
               (function emacs-command-loop-gui-after-key-dispatch)
               (function emacs-command-loop-gui-dispatch-key-request)
               (function emacs-command-loop-gui-dispatch-key-request-context)
               (function emacs-command-loop-gui-dispatch-key-request-current-context)
               (function emacs-command-loop-gui-run-request)
               (function emacs-command-loop-gui-run-request-context)
               (function emacs-command-loop-gui-run-request-current-context)
               (function emacs-command-loop-keymap-binding-p)
               (function emacs-command-loop-normalize-key-event)
               (function emacs-command-loop-key-dispatch-lane)
               (function emacs-command-loop-keyboard-quit-state)
               (variable emacs-command-loop-basic-edit-key-bindings)
               (function emacs-command-loop-install-basic-edit-key-bindings)
               (function emacs-command-loop-build-standard-keymap)
               (function emacs-command-loop-ensure-keymap-bindings)
               (variable emacs-command-loop-c-x-prefix-key-bindings)
               (function emacs-command-loop-install-c-x-prefix-key-bindings)
               (variable emacs-command-loop-help-prefix-key-bindings)
               (function emacs-command-loop-install-help-prefix-key-bindings)
               (function emacs-command-loop-key-dispatch-read-only-blocked-p)
               (function emacs-command-loop-key-dispatch-recording-p)
               (function emacs-command-loop-key-dispatch-execution-kind)
               (function emacs-command-loop-key-dispatch-direct-command-p)
               (function emacs-command-loop-key-dispatch-error-message)
               (function emacs-command-loop-key-dispatch-direct-funcall)
               (variable emacs-command-loop-key-dispatch-inline-command-alist)
               (function emacs-command-loop-key-dispatch-inline-command)
               (function emacs-command-loop-key-dispatch-record-inline-command)
               (function emacs-command-loop-key-dispatch-run-inline-edit)
               (function emacs-command-loop-key-dispatch-run-inline-kind)
               (function emacs-command-loop-key-dispatch-run-self-insert)
               (function emacs-command-loop-key-dispatch-run-plan)
               (function emacs-command-loop-menu-action-command)
               (function emacs-command-loop-run-menu-action-command)
               (function emacs-command-loop-command-name-symbol)
               (variable emacs-command-loop-command-feature-hints)
               (function emacs-command-loop-ensure-command)
               (function emacs-command-loop-dispatch-command-with-handlers)
               (function emacs-command-loop-run-extended-command)
               (function emacs-command-loop-repeat-last-command)
               (function emacs-command-loop-key-source-command-event)
               (variable emacs-command-loop-key-dispatch-non-mutating-commands)
               (function emacs-command-loop-key-dispatch-buffer-cache-invalidating-p)
               (function emacs-command-loop-key-dispatch-undo-boundary-p)
               (function emacs-command-loop-key-dispatch-cycle-reset-p)
               (function emacs-command-loop-key-dispatch-post-command-policy)
               (function emacs-command-loop-printable-self-insert-p)
               (function emacs-command-loop-key-dispatch-plan)
               (function emacs-command-loop-gui-replay-key-lines)
               (function emacs-command-loop-feed-events)
               (function emacs-command-loop-pending-p)
               (function emacs-command-loop-read-event)
               (function emacs-command-loop-read-char)
               (function emacs-command-loop-read-command)
               (function emacs-command-loop-clear-this-command-keys)
               (function emacs-command-loop-record-key)
               (function emacs-command-loop-this-command-keys)
               (function emacs-command-loop-this-command-keys-vector)
               (function emacs-command-loop-set-this-command)
               (function emacs-command-loop-mark-command-finished)
               (function emacs-command-loop-read-key-sequence)
               (function emacs-command-loop-read-key-sequence-vector)
               (function emacs-command-loop-call-interactively)
               (function emacs-command-loop-funcall-interactively)
               (function emacs-command-loop-command-execute)
               (function emacs-command-loop-step)
               (function emacs-command-loop-drain)
               (function emacs-command-loop-1)
               (function emacs-command-loop-keyboard-quit)
               (function emacs-command-loop-recursive-edit)
               (function emacs-command-loop-exit-recursive-edit)
               (function emacs-command-loop-abort-recursive-edit)
               (function emacs-command-loop-top-level)
               (function emacs-command-loop-recursion-depth)
               (function emacs-command-loop-universal-argument)
               (function emacs-command-loop-digit-argument)
               (function emacs-command-loop-negative-argument)
               (variable emacs-command-loop-gui-extended-command-candidate-names)
               (function emacs-command-loop-gui-extended-command-candidates)
               (variable emacs-command-loop-gui-command-registry-names)
               (function emacs-command-loop-gui-command-registered-p)
               (function emacs-command-loop-gui-command-accepted-p)
               (variable emacs-command-loop-gui-read-only-command-names)
               (function emacs-command-loop-gui-read-only-command-p)
               (variable emacs-command-loop-gui-prefix-command-names)
               (function emacs-command-loop-gui-prefix-command-p)
               (variable emacs-command-loop-gui-prefix-repeat-command-names)
               (function emacs-command-loop-gui-prefix-repeat-command-p)
               (variable emacs-command-loop-gui-prefix-invert-command-alist)
               (function emacs-command-loop-gui-prefix-inverted-command)
               (function emacs-command-loop-gui-prefix-arg-number)
               (function emacs-command-loop-gui-prefix-arg-absolute-number)
               (function emacs-command-loop-gui-prefix-number-string)
               (function emacs-command-loop-gui-prefix-digit-key)
               (function emacs-command-loop-gui-digit-argument)
               (function emacs-command-loop-gui-negative-argument)
               (function emacs-command-loop-gui-universal-argument)
               (function emacs-command-loop-gui-invert-prefix-command-if-needed)
               (function emacs-command-loop-gui-execute-with-prefix-arg)
               (variable emacs-command-loop-gui-adapted-command-alist)
               (function emacs-command-loop-gui-command-adapter-kind)
               (function emacs-command-loop-execute-extended-command)
               (variable emacs-help-gui-backend)
               (variable emacs-help-gui-arg)
               (variable emacs-help-gui-current-file-name)
               (variable emacs-help-gui-buffer-name)
               (variable emacs-help-gui-buffer-read-only-p)
               (variable emacs-help-gui-window-layout)
               (variable emacs-help-gui-keymap-source)
               (variable emacs-help-gui-user-keymap-source)
               (variable emacs-help-gui-minibuffer-keymap-source)
               (variable emacs-help-gui-status)
               (variable emacs-help-gui-standard-keymap-source-bindings)
               (function emacs-help-gui-standard-keymap-source)
               (function emacs-help-gui-register-backend)
               (function emacs-help-gui-set-context)
               (function emacs-help-gui-refresh-context-from-backend)
               (function emacs-help-prefix-candidates)
               (function emacs-help-describe-function-text)
               (function emacs-help-describe-variable-text)
               (function emacs-help-apropos-matches)
               (function emacs-help-apropos-text)
               (function emacs-help-key-vector-description)
               (function emacs-help-key-binding-summary)
               (function emacs-help-key-lookup-summary)
               (function emacs-help-key-event-description)
               (function emacs-help-gui-show-help-buffer)
               (function emacs-help-gui-describe-function-core)
               (function emacs-help-gui-describe-function)
               (function emacs-help-gui-describe-variable-core)
               (function emacs-help-gui-describe-variable)
               (function emacs-help-gui-describe-key-core)
               (function emacs-help-gui-describe-key)
               (function emacs-help-gui-describe-key-briefly-core)
               (function emacs-help-gui-describe-key-briefly)
               (function emacs-help-gui-describe-bindings-core)
               (function emacs-help-gui-describe-bindings)
               (function emacs-help-gui-help-for-help)
               (function emacs-help-gui-where-is-core)
               (function emacs-help-gui-where-is)
               (function emacs-help-gui-describe-command)
               (function emacs-help-gui-describe-symbol)
               (function emacs-help-gui-describe-package)
               (function emacs-help-gui-static-command)
               (function emacs-help-gui-apropos-command)
               (function emacs-help-gui-apropos-documentation)
               (function emacs-help-quit-window)
               (function emacs-help-revert-buffer)
               (function emacs-help-gui-describe-function-current-context-command)
               (function emacs-help-gui-describe-function-prompt-command)
               (function emacs-help-gui-describe-variable-current-context-command)
               (function emacs-help-gui-describe-variable-prompt-command)
               (function emacs-help-gui-describe-key-current-context-command)
               (function emacs-help-gui-begin-key-help-command)
               (function emacs-help-gui-consume-key-help-event)
               (function emacs-help-gui-run-key-help-command)
               (function emacs-help-gui-describe-key-briefly-current-context-command)
               (function emacs-help-gui-describe-bindings-current-context-command)
               (function emacs-help-gui-where-is-current-context-command)
               (function emacs-help-gui-help-for-help-current-context-command)
               (function emacs-help-gui-describe-command-current-context-command)
               (function emacs-help-gui-describe-package-current-context-command)
               (function emacs-help-gui-static-current-context-command)
               (function emacs-help-gui-apropos-command-current-context-command)
               (function emacs-help-gui-apropos-command-prompt-command)
               (function emacs-help-gui-apropos-documentation-current-context-command)
               (function emacs-help-gui-apropos-documentation-prompt-command)
               (function emacs-help-gui-writeback-spec)
               (function emacs-help-gui-writeback-spec-flag)
               (function emacs-help-gui-writeback-state)
               (function emacs-help-gui-current-context-command)
               (function emacs-info-gui-header-field)
               (function emacs-info-gui-render-node)
               (function emacs-info-gui-info-core)
               (function emacs-info-gui-info)
               (function emacs-info-gui-goto-pointer)
               (function emacs-info-gui-next)
               (function emacs-info-gui-prev)
               (function emacs-info-gui-up)
               (function emacs-info-gui-emacs-manual)
               (function emacs-info-gui-display-manual)
               (function emacs-info-gui-view-order-manuals)
               (function emacs-info-gui-goto-emacs-command-node)
               (function emacs-info-gui-goto-emacs-key-command-node)
               (function emacs-info-gui-lookup-symbol)
               (function emacs-info-gui-info-command)
               (function emacs-info-gui-info-current-context-command)
               (function emacs-info-gui-next-command)
               (function emacs-info-gui-register-backend)
               (function emacs-info-gui-prev-command)
               (function emacs-info-gui-up-command)
               (function emacs-info-gui-next-current-context-command)
               (function emacs-info-gui-prev-current-context-command)
               (function emacs-info-gui-up-current-context-command)
               (function emacs-info-gui-emacs-manual-command)
               (function emacs-info-gui-display-manual-command)
               (function emacs-info-gui-view-order-manuals-command)
               (function emacs-info-gui-goto-emacs-command-node-command)
               (function emacs-info-gui-goto-emacs-key-command-node-command)
               (function emacs-info-gui-lookup-symbol-command)
               (function emacs-info-gui-emacs-manual-current-context-command)
               (function emacs-info-gui-display-manual-current-context-command)
               (function emacs-info-gui-view-order-manuals-current-context-command)
               (function emacs-info-gui-goto-emacs-command-node-current-context-command)
               (function emacs-info-gui-goto-emacs-key-command-node-current-context-command)
               (function emacs-info-gui-lookup-symbol-current-context-command)
               (function emacs-info-gui-current-context-command)
               (function emacs-info-run-current-context-command)
               (function emacs-info-gui-writeback-spec)
               (function emacs-info-gui-writeback-spec-flag)
               (function emacs-info-gui-writeback-state)
               (function emacs-info-gui-set-context)
               (function emacs-info-gui-refresh-context-from-backend)
               (variable emacs-info-gui-backend)
               (variable emacs-info-gui-arg)
               (variable emacs-info-gui-status)
               (variable emacs-info-gui-buffer-name)
               (variable emacs-info-gui-file)
               (variable emacs-info-gui-node)
               (variable emacs-info-gui-scan-cap)))
    (textmodes-stub
     :owner FEAT
     :package-id nelisp-emacs-textmodes-stub
     :symbols ((function emacs-textmodes-fill-region)
               (function emacs-textmodes-count-matches))))
  "Stable package APIs exposed by the `nelisp-emacs' facade.
This is intentionally narrower than the generated public API inventory.
Symbols enter this manifest only after package-owner review with test and
consumer-facing documentation evidence.")

(defconst nelisp-emacs-library-stable-lazy-package-api
  '((text-core
     :owner TXT
     :package-id nelisp-emacs-text-core
     :feature nelisp-coding-jis-tables
     :symbols ((variable nelisp-coding-shift-jis-x0208-decode-table)
               (variable nelisp-coding-cp932-extension-decode-table)
               (variable nelisp-coding-euc-jp-x0208-decode-table)
               (variable nelisp-coding-euc-jp-x0212-decode-table)
               (variable nelisp-coding-jis-tables-sha256)))
    (io
     :owner IO
     :package-id nelisp-emacs-io
     :feature nemacs-loaddefs
     :symbols ((function nemacs-loaddefs-generate-for-file)
               (function nemacs-loaddefs-generate)))
    (core
     :owner CORE
     :package-id nelisp-emacs-core
     :feature emacs-tui-backend
     :symbols ((function emacs-tui-backend-emit)
               (function emacs-tui-backend-frame-set-dirty-rows)
               (function emacs-tui-backend-init)
               (function emacs-tui-backend-shutdown)
               (function emacs-tui-backend-enter-alt-screen)
               (function emacs-tui-backend-leave-alt-screen)
               (function emacs-tui-backend-capabilities)
               (function emacs-tui-backend-get-capability)
               (function emacs-tui-backend-frame-create)
               (function emacs-tui-backend-frame-destroy)
               (function emacs-tui-backend-frame-resize)
               (function emacs-tui-backend-canvas-clear)
               (function emacs-tui-backend-canvas-draw-text)
               (function emacs-tui-backend-canvas-flush)
               (function emacs-tui-backend-event-poll)
               (function emacs-tui-backend-event-inject)
               (function emacs-tui-backend-cursor-show)
               (function emacs-tui-backend-cursor-show-if-changed)
               (function emacs-tui-backend-cursor-hide)
               (function emacs-tui-backend-resize-listen)
               (variable emacs-tui-backend-frame-stub-invariant-version)
               (variable emacs-tui-backend-degrade-contract-version)
               (variable emacs-tui-backend-event-source-contract-version)
               (variable emacs-tui-backend-frame-default-width)
               (variable emacs-tui-backend-frame-default-height)
               (variable emacs-tui-backend-output-fn)
               (variable emacs-tui-backend-color-mode)
               (variable emacs-tui-backend-log-enabled)
               (variable emacs-tui-backend-base-capabilities)))
    (core
     :owner CORE
     :package-id nelisp-emacs-core
     :feature emacs-tui-terminfo
     :symbols ((function emacs-tui-terminfo-detect)
               (function emacs-tui-terminfo-from-env)
               (function emacs-tui-terminfo-clear-cache)
               (function emacs-tui-terminfo-supports-p)
               (function emacs-tui-terminfo-color-mode)
               (function emacs-tui-terminfo-capabilities)
               (function emacs-tui-terminfo-known-terminals)
               (function emacs-tui-terminfo-mvp-capabilities)
               (function emacs-tui-terminfo-backend-init-args)
               (variable emacs-tui-terminfo-default-term)
               (variable emacs-tui-terminfo-extra-color-terminals)
               (variable emacs-tui-terminfo-cache-enabled)
               (variable emacs-tui-terminfo-detect-contract-version)
               (variable emacs-tui-terminfo-mvp-capability-list)))
    (core
     :owner CORE
     :package-id nelisp-emacs-core
     :feature emacs-tui-event
     :symbols ((function emacs-tui-event-init)
               (function emacs-tui-event-shutdown)
               (function emacs-tui-event-encode-key-event)
               (function emacs-tui-event-decode-csi)
               (function emacs-tui-event-control-char-name)
               (function emacs-tui-event-parse-byte-stream)
               (function emacs-tui-event-pending-event-p)
               (function emacs-tui-event-feed-bytes)
               (function emacs-tui-event-poll-printable-byte)
               (function emacs-tui-event-poll)
               (function emacs-tui-event-install-sigwinch)
               (function emacs-tui-event-uninstall-sigwinch)
               (function emacs-tui-event-current-window-size)
               (function emacs-tui-event-dispatch-resize)
               (variable emacs-tui-event-source-contract-version)
               (variable emacs-tui-event-default-window-width)
               (variable emacs-tui-event-default-window-height)
               (variable emacs-tui-event-input-fn)
               (variable emacs-tui-event-log-enabled))))
  "Stable package APIs exposed through explicit lazy companion features.
These symbols are part of the reusable package contract, but they are not
loaded by requiring `nelisp-emacs'.  Consumers must require the entry's
`:feature' before relying on the listed symbols.")

(defun nelisp-emacs--copy-package-plist (plist)
  "Return a copy of package PLIST with copied list values."
  (let ((copy (copy-sequence plist)))
    (dolist (key '(:features :lazy-features))
      (let ((value (plist-get copy key)))
        (plist-put copy key (and value (copy-sequence value)))))
    copy))

(defun nelisp-emacs--copy-stable-api-entry (entry)
  "Return a copy of stable API ENTRY."
  (let ((copy (copy-sequence (cdr entry))))
    (plist-put copy :symbols
               (mapcar #'copy-sequence (plist-get copy :symbols)))
    (cons (car entry) copy)))

(defun nelisp-emacs-library-package-manifest ()
  "Return a copy of `nelisp-emacs-library-packages'."
  (mapcar
   (lambda (entry)
     (cons (car entry)
           (nelisp-emacs--copy-package-plist (cdr entry))))
   nelisp-emacs-library-packages))

(defun nelisp-emacs-library-stable-api-manifest ()
  "Return a copy of the stable package API manifest."
  (mapcar #'nelisp-emacs--copy-stable-api-entry
          nelisp-emacs-library-stable-package-api))

(defun nelisp-emacs-library-stable-api-symbols (&optional package)
  "Return stable package API symbols.
When PACKAGE is non-nil, return only symbols for that reusable package
group.  Without PACKAGE, return all stable package API symbols."
  (let ((entries (if package
                     (let ((entry
                            (assq package
                                  nelisp-emacs-library-stable-package-api)))
                       (and entry (list entry)))
                   nelisp-emacs-library-stable-package-api))
        symbols)
    (dolist (entry entries)
      (dolist (spec (plist-get (cdr entry) :symbols))
        (push (nth 1 spec) symbols)))
    (nreverse symbols)))

(defun nelisp-emacs-library-stable-api-entry (symbol)
  "Return stable package API metadata for SYMBOL, or nil.
The returned plist contains `:package', `:owner', `:package-id', and
`:kind'."
  (catch 'found
    (dolist (entry nelisp-emacs-library-stable-package-api)
      (let ((package (car entry))
            (plist (cdr entry)))
        (dolist (spec (plist-get plist :symbols))
          (when (eq (nth 1 spec) symbol)
            (throw 'found
                   (list :package package
                         :owner (plist-get plist :owner)
                         :package-id (plist-get plist :package-id)
                         :kind (nth 0 spec)))))))
    nil))

(defun nelisp-emacs-library-stable-lazy-api-manifest ()
  "Return a copy of the stable lazy package API manifest."
  (mapcar #'nelisp-emacs--copy-stable-api-entry
          nelisp-emacs-library-stable-lazy-package-api))

(defun nelisp-emacs-library-stable-lazy-api-symbols (&optional package)
  "Return stable lazy package API symbols.
When PACKAGE is non-nil, return only symbols for that reusable package
group.  Without PACKAGE, return all stable lazy package API symbols."
  (let (entries symbols)
    (if package
        (progn
          (dolist (entry nelisp-emacs-library-stable-lazy-package-api)
            (when (eq (car entry) package)
              (push entry entries)))
          (setq entries (nreverse entries)))
      (setq entries nelisp-emacs-library-stable-lazy-package-api))
    (dolist (entry entries)
      (dolist (spec (plist-get (cdr entry) :symbols))
        (push (nth 1 spec) symbols)))
    (nreverse symbols)))

(defun nelisp-emacs-library-stable-lazy-api-entry (symbol)
  "Return stable lazy package API metadata for SYMBOL, or nil.
The returned plist contains `:package', `:owner', `:package-id',
`:feature', and `:kind'.  Consumers must require `:feature' before
relying on SYMBOL."
  (catch 'found
    (dolist (entry nelisp-emacs-library-stable-lazy-package-api)
      (let ((package (car entry))
            (plist (cdr entry)))
        (dolist (spec (plist-get plist :symbols))
          (when (eq (nth 1 spec) symbol)
            (throw 'found
                   (list :package package
                         :owner (plist-get plist :owner)
                         :package-id (plist-get plist :package-id)
                         :feature (plist-get plist :feature)
                         :kind (nth 0 spec)))))))
    nil))

(defun nelisp-emacs-library-package-names ()
  "Return reusable package group names exposed by `nelisp-emacs'."
  (mapcar #'car nelisp-emacs-library-packages))

(defun nelisp-emacs-library-package (name)
  "Return a copy of reusable package group NAME's plist, or nil.
The returned plist contains `:owner', `:feature', `:features', and
`:lazy-features'."
  (let ((entry (assq name nelisp-emacs-library-packages)))
    (when entry
      (nelisp-emacs--copy-package-plist (cdr entry)))))

(defun nelisp-emacs-library-package-features (name)
  "Return a copy of reusable package group NAME's member features."
  (let ((package (nelisp-emacs-library-package name)))
    (and package (plist-get package :features))))

(defun nelisp-emacs-library-package-lazy-features (name)
  "Return a copy of reusable package group NAME's lazy companion features."
  (let ((package (nelisp-emacs-library-package name)))
    (and package (plist-get package :lazy-features))))

(provide 'nelisp-emacs)

;;; nelisp-emacs.el ends here
